/**
 * Curated PFAF-style plant registry. Each entry has:
 *  - id: stable lowercase ascii key (no spaces)
 *  - common name in Spanish
 *  - scientific name
 *  - aliases: alternate common names (other regions)
 *  - emoji (legacy, retained for any non-codex contexts)
 *  - spacing in metres (mature canopy diameter)
 *  - sun preference, hardiness zones, plant type, origin
 *  - functions (food / medicine / soil / pollinator / etc)
 *  - notes (one-paragraph description)
 *  - companions / clash pairs by id
 *
 * Data is hand-curated based on PFAF (Plants For A Future) database descriptions
 * and regional knowledge for Latin America. Subset chosen for the demo;
 * meant to be extended via the in-app "Nueva planta" form.
 */

export type PdbEntry = {
  e: string;
  n: string;
  sci: string;
  aliases?: string[];
  sp: number;
  sun: 'completo' | 'parcial' | 'sombra';
  zn: number[];
  type: 'arbol-alto' | 'arbol-medio' | 'arbusto' | 'herbaceo' | 'trepadora' | 'cobertura';
  origin: 'native' | 'adapted' | 'invasive';
  /**
   * Optional region tag(s) used for filtering suggestions.
   * Keep them short and stable (e.g. "andes", "caribe", "mesoamerica", "amazonia").
   */
  regions?: string[];
  /**
   * Optional microclimate tag(s) used for filtering suggestions.
   * Examples: "ladera", "fondo-valle", "cerca-agua", "cortaviento", "sombra-parcial".
   */
  microclimates?: string[];
  functions: string[];
  notes: string;
  edible_parts?: string[];
  companions: string[];
  clash: string[];
};

export const PDB: Record<string, PdbEntry> = {
  aguacate:    { e: '🥑', n: 'Aguacate',    sci: 'Persea americana',     aliases: ['palta'],     sp: 10,  sun: 'parcial',  zn: [3, 4],     type: 'arbol-alto',  origin: 'native',   functions: ['comestible', 'medicinal'], edible_parts: ['fruto'], notes: 'Dosel de raíces superficiales. Sensible al encharcamiento. Aporta sombra al cafetal y crea microclima.', companions: ['cafe', 'platano', 'frijol'], clash: ['yuca'] },
  mango:       { e: '🥭', n: 'Mango',       sci: 'Mangifera indica',                              sp: 12,  sun: 'completo', zn: [3, 4],     type: 'arbol-alto',  origin: 'adapted',  functions: ['comestible'], edible_parts: ['fruto'], notes: 'Dosel productivo en tropical cálido. Soporta sequía moderada una vez establecido.', companions: ['cafe', 'platano'], clash: [] },
  chachafruto: { e: '🌳', n: 'Chachafruto', sci: 'Erythrina edulis',     aliases: ['balú', 'sachapuruto'], sp: 8, sun: 'completo', zn: [2, 3, 4], type: 'arbol-alto', origin: 'native', functions: ['comestible', 'fija-n', 'madera'], edible_parts: ['semilla'], notes: 'Fija nitrógeno. Excelente cerca viva y forraje. Semillas comestibles cocidas.', companions: ['cafe', 'yuca', 'frijol'], clash: [] },
  guanabana:   { e: '🌲', n: 'Guanábana',   sci: 'Annona muricata',                                sp: 7,   sun: 'parcial',  zn: [3, 4],     type: 'arbol-medio', origin: 'native',   functions: ['comestible', 'medicinal'], edible_parts: ['fruto'], notes: 'Sensible a vientos fuertes. Hojas con uso medicinal tradicional.', companions: ['cafe', 'platano'], clash: [] },
  platano:     { e: '🍌', n: 'Plátano',     sci: 'Musa × paradisiaca',                             sp: 3,   sun: 'parcial',  zn: [1, 2, 3],  type: 'arbol-medio', origin: 'adapted',  functions: ['comestible'], edible_parts: ['fruto'], notes: 'Sombra rápida. Hojas excelentes como mantillo. Banano ornamental similar.', companions: ['cafe', 'aguacate', 'frijol'], clash: [] },
  cafe:        { e: '☕', n: 'Café',         sci: 'Coffea arabica',                                 sp: 2.5, sun: 'parcial',  zn: [2, 3],     type: 'arbusto',     origin: 'adapted',  functions: ['comestible'], edible_parts: ['semilla'], notes: 'Necesita sombra moderada. Crece bien bajo aguacate, plátano o guamo.', companions: ['aguacate', 'platano', 'chachafruto', 'guamo'], clash: [] },
  yuca:        { e: '🌿', n: 'Yuca',         sci: 'Manihot esculenta',    aliases: ['mandioca', 'casava'], sp: 1.2, sun: 'completo', zn: [2, 3], type: 'arbusto', origin: 'native', functions: ['comestible'], edible_parts: ['raíz'], notes: 'Tolerante a sequía. Raíz energética. Hojas tóxicas crudas.', companions: ['frijol', 'platano', 'chachafruto'], clash: ['aguacate'] },
  aji:         { e: '🌶️', n: 'Ají',          sci: 'Capsicum spp.',        aliases: ['chile'],     sp: 0.8, sun: 'completo', zn: [1, 2],     type: 'herbaceo',    origin: 'native',   functions: ['comestible', 'medicinal', 'polinizador'], edible_parts: ['fruto'], notes: 'Muchas variedades nativas. Excelente en bordes. Repele algunas plagas.', companions: ['frijol', 'cilantro'], clash: [] },
  frijol:      { e: '🫘', n: 'Fríjol',       sci: 'Phaseolus vulgaris',                            sp: 0.4, sun: 'completo', zn: [1, 2, 3],  type: 'herbaceo',    origin: 'native',   functions: ['comestible', 'fija-n'], edible_parts: ['semilla', 'vaina'], notes: 'Fija nitrógeno. Excelente cobertura y rotación. Trepa en milpa.', companions: ['aguacate', 'yuca', 'aji', 'maiz'], clash: [] },
  cilantro:    { e: '🌱', n: 'Cilantro',     sci: 'Coriandrum sativum',                            sp: 0.3, sun: 'parcial',  zn: [1],        type: 'herbaceo',    origin: 'adapted',  functions: ['comestible', 'medicinal', 'polinizador'], edible_parts: ['hoja', 'semilla'], notes: 'Ciclo rápido. Auto-siembra. Atrae polinizadores cuando florece.', companions: ['aji', 'frijol'], clash: [] },
  maiz:        { e: '🌽', n: 'Maíz',         sci: 'Zea mays',             aliases: ['choclo'],    sp: 0.7, sun: 'completo', zn: [2, 3],     type: 'herbaceo',    origin: 'native',   functions: ['comestible'], edible_parts: ['semilla'], notes: 'Milpa tradicional con fríjol y calabaza. Tutor natural para enredaderas.', companions: ['frijol', 'calabaza'], clash: [] },
  girasol:     { e: '🌻', n: 'Girasol',      sci: 'Helianthus annuus',                             sp: 0.6, sun: 'completo', zn: [1, 2],     type: 'herbaceo',    origin: 'adapted',  functions: ['polinizador', 'comestible'], edible_parts: ['semilla'], notes: 'Atrae abejas y aves. Buen tutor para fríjol bajo. Alelopatía leve con papas.', companions: ['frijol', 'maiz'], clash: ['papa'] },
  cacao:       { e: '🍫', n: 'Cacao',        sci: 'Theobroma cacao',                               sp: 4,   sun: 'sombra',   zn: [3, 4],     type: 'arbol-medio', origin: 'native',   functions: ['comestible'], edible_parts: ['semilla', 'pulpa'], notes: 'Necesita sombra y humedad alta. Va bajo dosel de banano o guamo.', companions: ['platano', 'guamo'], clash: [] },
  papaya:      { e: '🥭', n: 'Papaya',       sci: 'Carica papaya',                                 sp: 2,   sun: 'completo', zn: [3, 4],     type: 'arbol-medio', origin: 'native',   functions: ['comestible', 'medicinal'], edible_parts: ['fruto'], notes: 'Frutece en su primer año. Sensible al frío y al viento.', companions: ['frijol', 'platano'], clash: [] },
  guamo:       { e: '🌳', n: 'Guamo',        sci: 'Inga edulis',                                   sp: 8,   sun: 'completo', zn: [2, 3, 4],  type: 'arbol-alto',  origin: 'native',   functions: ['comestible', 'fija-n', 'sombra'], edible_parts: ['fruto'], notes: 'Fija nitrógeno. Sombra clásica para cafetales y cacaotales.', companions: ['cafe', 'cacao'], clash: [] },
  calabaza:    { e: '🎃', n: 'Calabaza',     sci: 'Cucurbita spp.',       aliases: ['ahuyama', 'zapallo'], sp: 1.5, sun: 'completo', zn: [1, 2], type: 'cobertura', origin: 'native', functions: ['comestible'], edible_parts: ['fruto', 'semilla', 'flor'], notes: 'Cobertura viva. Hojas grandes sombrean el suelo. Tercera hermana en la milpa.', companions: ['maiz', 'frijol'], clash: [] },
  papa:        { e: '🥔', n: 'Papa',         sci: 'Solanum tuberosum',    aliases: ['patata'],     sp: 0.4, sun: 'completo', zn: [2, 3],     type: 'herbaceo',    origin: 'native',   functions: ['comestible'], edible_parts: ['raíz'], notes: 'Andina por excelencia. Muchas variedades nativas resistentes a heladas.', companions: ['frijol', 'maiz'], clash: ['girasol'] },
  quinua:      { e: '🌾', n: 'Quinua',       sci: 'Chenopodium quinoa',                             sp: 0.5, sun: 'completo', zn: [3, 4],     type: 'herbaceo',    origin: 'native',   functions: ['comestible'], edible_parts: ['semilla', 'hoja'], notes: 'Andina, alta proteína. Resiste sequía moderada y suelos pobres.', companions: ['frijol', 'papa'], clash: [] },
  amaranto:    { e: '🌾', n: 'Amaranto',     sci: 'Amaranthus spp.',      aliases: ['kiwicha'],   sp: 0.6, sun: 'completo', zn: [2, 3],     type: 'herbaceo',    origin: 'native',   functions: ['comestible'], edible_parts: ['semilla', 'hoja'], notes: 'Hojas como espinaca. Semillas con alto valor nutricional.', companions: ['maiz', 'frijol'], clash: [] },
  tomate:      { e: '🍅', n: 'Tomate',       sci: 'Solanum lycopersicum', aliases: ['jitomate'],  sp: 0.6, sun: 'completo', zn: [1, 2],     type: 'herbaceo',    origin: 'native',   functions: ['comestible'], edible_parts: ['fruto'], notes: 'Necesita tutor. Cuidado con tizones en clima húmedo.', companions: ['cilantro', 'aji'], clash: ['papa'] },
  cebolla:     { e: '🧅', n: 'Cebolla',      sci: 'Allium cepa',                                   sp: 0.2, sun: 'completo', zn: [1, 2],     type: 'herbaceo',    origin: 'adapted',  functions: ['comestible', 'medicinal'], edible_parts: ['bulbo', 'hoja'], notes: 'Repele plagas en zona 1. Compañera clásica del tomate y zanahoria.', companions: ['tomate', 'zanahoria', 'lechuga'], clash: ['frijol'] },
  ajo:         { e: '🧄', n: 'Ajo',          sci: 'Allium sativum',                                sp: 0.15, sun: 'completo', zn: [1, 2],    type: 'herbaceo',    origin: 'adapted',  functions: ['comestible', 'medicinal'], edible_parts: ['bulbo'], notes: 'Repele insectos. Excelente borde de huerta.', companions: ['tomate', 'zanahoria'], clash: ['frijol'] },
  zanahoria:   { e: '🥕', n: 'Zanahoria',    sci: 'Daucus carota',                                 sp: 0.15, sun: 'completo', zn: [1, 2],    type: 'herbaceo',    origin: 'adapted',  functions: ['comestible'], edible_parts: ['raíz'], notes: 'Suelos sueltos y profundos. Compañera de cebolla.', companions: ['cebolla', 'ajo', 'lechuga'], clash: [] },
  lechuga:     { e: '🥬', n: 'Lechuga',      sci: 'Lactuca sativa',                                sp: 0.3, sun: 'parcial',  zn: [1, 2],     type: 'herbaceo',    origin: 'adapted',  functions: ['comestible'], edible_parts: ['hoja'], notes: 'Ciclo corto. Excelente intercalada con zanahoria.', companions: ['zanahoria', 'cebolla'], clash: [] },
  acelga:      { e: '🥬', n: 'Acelga',       sci: 'Beta vulgaris cicla',                            sp: 0.3, sun: 'parcial',  zn: [1, 2],     type: 'herbaceo',    origin: 'adapted',  functions: ['comestible'], edible_parts: ['hoja'], notes: 'Resiste cortes repetidos. Hojas grandes nutritivas.', companions: ['cebolla'], clash: [] },
  espinaca:    { e: '🥬', n: 'Espinaca',     sci: 'Spinacia oleracea',                              sp: 0.25, sun: 'parcial', zn: [1, 2],     type: 'herbaceo',    origin: 'adapted',  functions: ['comestible'], edible_parts: ['hoja'], notes: 'Prefiere clima fresco. Buena intercalada bajo árboles jóvenes.', companions: ['frijol'], clash: [] },
  rabano:      { e: '🥗', n: 'Rábano',       sci: 'Raphanus sativus',                               sp: 0.1, sun: 'completo', zn: [1, 2],     type: 'herbaceo',    origin: 'adapted',  functions: ['comestible'], edible_parts: ['raíz', 'hoja'], notes: 'Cosecha en 25–30 días. Rompe la costra del suelo.', companions: ['lechuga', 'zanahoria'], clash: [] },
  remolacha:   { e: '🥔', n: 'Remolacha',    sci: 'Beta vulgaris',                                  sp: 0.2, sun: 'completo', zn: [1, 2],     type: 'herbaceo',    origin: 'adapted',  functions: ['comestible'], edible_parts: ['raíz', 'hoja'], notes: 'Hojas comestibles. Acumula azúcar en suelo bien drenado.', companions: ['cebolla', 'lechuga'], clash: [] },
  mora:        { e: '🫐', n: 'Mora',          sci: 'Rubus glaucus',                                  sp: 1.5, sun: 'parcial',  zn: [3, 4],     type: 'arbusto',     origin: 'native',   functions: ['comestible', 'medicinal'], edible_parts: ['fruto'], notes: 'Andina. Espinosa. Forma cercas vivas productivas.', companions: ['platano'], clash: [] },
  fresa:       { e: '🍓', n: 'Fresa',         sci: 'Fragaria × ananassa',                            sp: 0.3, sun: 'parcial',  zn: [1, 2],     type: 'cobertura',   origin: 'adapted',  functions: ['comestible'], edible_parts: ['fruto'], notes: 'Cobertura comestible bajo frutales. Multiplica por estolones.', companions: ['cebolla', 'ajo'], clash: [] },
  ruda:        { e: '🌿', n: 'Ruda',          sci: 'Ruta graveolens',                                sp: 0.6, sun: 'completo', zn: [1, 2],     type: 'arbusto',     origin: 'adapted',  functions: ['medicinal', 'repelente'], edible_parts: [], notes: 'Repele algunas plagas. Cuidado: irritante al contacto en sol.', companions: ['rosal'], clash: ['albahaca'] },
  manzanilla:  { e: '🌼', n: 'Manzanilla',    sci: 'Matricaria chamomilla', aliases: ['chamomila'], sp: 0.3, sun: 'completo', zn: [1, 2],     type: 'herbaceo',    origin: 'adapted',  functions: ['medicinal', 'polinizador'], edible_parts: ['flor'], notes: 'Té calmante. Atrae polinizadores. Auto-siembra.', companions: ['cebolla'], clash: [] },
  hierbabuena: { e: '🌿', n: 'Hierbabuena',   sci: 'Mentha spicata',                                  sp: 0.4, sun: 'parcial',  zn: [1, 2],     type: 'cobertura',   origin: 'adapted',  functions: ['medicinal', 'comestible'], edible_parts: ['hoja'], notes: 'Invasiva: contén con borde físico. Repele hormigas.', companions: ['platano'], clash: ['cebolla'] },
  romero:      { e: '🌿', n: 'Romero',        sci: 'Salvia rosmarinus',                              sp: 0.8, sun: 'completo', zn: [2, 3],     type: 'arbusto',     origin: 'adapted',  functions: ['medicinal', 'comestible', 'polinizador'], edible_parts: ['hoja'], notes: 'Tolera sequía. Atrae abejas. Borde aromático perenne.', companions: ['frijol'], clash: [] },
  caña:        { e: '🌾', n: 'Caña de azúcar', sci: 'Saccharum officinarum',                          sp: 1.2, sun: 'completo', zn: [3, 4],     type: 'herbaceo',    origin: 'adapted',  functions: ['comestible'], edible_parts: ['tallo'], notes: 'Cortavientos productivo. Tallo dulce. Cosecha cada 12–18 meses.', companions: ['platano'], clash: [] },
  pina:        { e: '🍍', n: 'Piña',          sci: 'Ananas comosus',                                 sp: 0.8, sun: 'completo', zn: [3, 4],     type: 'cobertura',   origin: 'native',   functions: ['comestible'], edible_parts: ['fruto'], notes: 'Cobertura espinosa. Bordes comestibles. Tarda 18 meses.', companions: ['platano'], clash: [] },
  pasiflora:   { e: '🌸', n: 'Maracuyá',      sci: 'Passiflora edulis',     aliases: ['parchita'], sp: 1,   sun: 'completo', zn: [3, 4],     type: 'trepadora',   origin: 'native',   functions: ['comestible', 'polinizador'], edible_parts: ['fruto'], notes: 'Trepadora vigorosa. Atrae polinizadores con flores grandes.', companions: ['platano'], clash: [] },
  lulo:        { e: '🍊', n: 'Lulo',          sci: 'Solanum quitoense',     aliases: ['naranjilla'], sp: 1.2, sun: 'parcial', zn: [3, 4],    type: 'arbusto',     origin: 'native',   functions: ['comestible'], edible_parts: ['fruto'], notes: 'Andino tropical. Pelos urticantes en hojas. Pulpa muy ácida.', companions: ['platano'], clash: [] },
  ortiga:      { e: '🌿', n: 'Ortiga',        sci: 'Urtica dioica',                                  sp: 0.4, sun: 'parcial',  zn: [2, 3],     type: 'herbaceo',    origin: 'adapted',  functions: ['medicinal', 'biocida'], edible_parts: ['hoja'], notes: 'Buena planta indicadora de suelos ricos en N. Hojas hervidas pierden urticación.', companions: [], clash: [] },

  // ---- Frutales adicionales (PFAF / regional) ----
  citrico:        { e: '🍊', n: 'Naranjo',        sci: 'Citrus × sinensis',     aliases: ['naranja dulce'], sp: 6,    sun: 'completo', zn: [2, 3],     type: 'arbol-medio', origin: 'adapted',  functions: ['comestible'], edible_parts: ['fruto', 'flor'], notes: 'Frutal de altura tropical-media. Polinizado por abejas; flores muy aromáticas.', companions: ['cafe', 'guamo'], clash: [] },
  limon:          { e: '🍋', n: 'Limón',          sci: 'Citrus × limon',                                sp: 5,    sun: 'completo', zn: [2, 3],     type: 'arbol-medio', origin: 'adapted',  functions: ['comestible', 'medicinal'], edible_parts: ['fruto', 'hoja'], notes: 'Producción casi continua. Sensible a heladas. Hojas para infusión.', companions: ['cafe'], clash: [] },
  guayabo:        { e: '🍈', n: 'Guayabo',        sci: 'Psidium guajava',                               sp: 5,    sun: 'completo', zn: [2, 3, 4],  type: 'arbol-medio', origin: 'native',   functions: ['comestible', 'medicinal'], edible_parts: ['fruto', 'hoja'], notes: 'Rústico. Hojas con uso digestivo. Atrae fauna polinizadora y dispersora.', companions: ['platano'], clash: [] },
  granadilla:     { e: '🟡', n: 'Granadilla',     sci: 'Passiflora ligularis',                          sp: 1,    sun: 'completo', zn: [3, 4],     type: 'trepadora',   origin: 'native',   functions: ['comestible'], edible_parts: ['fruto'], notes: 'Trepadora andina. Necesita tutor o pérgola robusta. Frutos amarillos cuajados en pocos meses.', companions: ['cafe'], clash: [] },
  tomate_arbol:   { e: '🍅', n: 'Tomate de árbol', sci: 'Solanum betaceum',     aliases: ['tamarillo'], sp: 2,    sun: 'parcial',  zn: [3, 4],     type: 'arbusto',     origin: 'native',   functions: ['comestible'], edible_parts: ['fruto'], notes: 'Andino. Vida útil 4–6 años. Cuidado con plagas de la familia Solanaceae.', companions: ['platano'], clash: ['tomate'] },
  uchuva:         { e: '🟠', n: 'Uchuva',         sci: 'Physalis peruviana',    aliases: ['aguaymanto'], sp: 0.8, sun: 'completo', zn: [2, 3],     type: 'arbusto',     origin: 'native',   functions: ['comestible', 'medicinal'], edible_parts: ['fruto'], notes: 'Frutos en cáliz. Auto-siembra prolífica. Excelente complemento andino.', companions: ['frijol'], clash: [] },
  curuba:         { e: '🟢', n: 'Curuba',         sci: 'Passiflora tarminiana',                         sp: 1.2,  sun: 'completo', zn: [3, 4],     type: 'trepadora',   origin: 'native',   functions: ['comestible'], edible_parts: ['fruto'], notes: 'Pasiflora andina de altura. Soporta climas frescos.', companions: [], clash: [] },
  pitaya:         { e: '🩷', n: 'Pitaya',         sci: 'Hylocereus undatus',    aliases: ['fruta del dragón'], sp: 1, sun: 'completo', zn: [3, 4], type: 'trepadora', origin: 'native', functions: ['comestible'], edible_parts: ['fruto'], notes: 'Cactus columnar; necesita tutor. Floración nocturna polinizada por murciélagos.', companions: [], clash: [] },
  cocotero:       { e: '🥥', n: 'Cocotero',       sci: 'Cocos nucifera',                                 sp: 8,    sun: 'completo', zn: [4],        type: 'arbol-alto',  origin: 'adapted',  functions: ['comestible'], edible_parts: ['fruto', 'savia'], notes: 'Costero. Tolera salinidad. Producción larga vida.', companions: [], clash: [] },
  arazá:          { e: '🟡', n: 'Arazá',          sci: 'Eugenia stipitata',                              sp: 4,    sun: 'parcial',  zn: [4],        type: 'arbol-medio', origin: 'native',   functions: ['comestible'], edible_parts: ['fruto'], notes: 'Amazónico. Frutos muy ácidos para jugos y conservas.', companions: ['platano'], clash: [] },
  copoazu:        { e: '🟫', n: 'Copoazú',        sci: 'Theobroma grandiflorum',                         sp: 6,    sun: 'sombra',   zn: [4],        type: 'arbol-medio', origin: 'native',   functions: ['comestible'], edible_parts: ['fruto', 'semilla'], notes: 'Pariente del cacao. Pulpa aromática para postres.', companions: ['cacao', 'platano'], clash: [] },
  borojo:         { e: '🟫', n: 'Borojó',         sci: 'Borojoa patinoi',                                sp: 4,    sun: 'sombra',   zn: [4],        type: 'arbol-medio', origin: 'native',   functions: ['comestible', 'medicinal'], edible_parts: ['fruto'], notes: 'Pacífico colombiano. Pulpa muy densa, energética.', companions: ['cacao'], clash: [] },
  acai:           { e: '🟣', n: 'Açaí',           sci: 'Euterpe oleracea',                               sp: 4,    sun: 'parcial',  zn: [4],        type: 'arbol-alto',  origin: 'native',   functions: ['comestible'], edible_parts: ['fruto'], notes: 'Palma amazónica. Multi-tallo; tolera inundaciones cortas.', companions: [], clash: [] },

  // ---- Raíces / tubérculos ----
  arracacha:      { e: '🥕', n: 'Arracacha',      sci: 'Arracacia xanthorrhiza',                         sp: 0.5,  sun: 'parcial',  zn: [2, 3],     type: 'herbaceo',    origin: 'native',   functions: ['comestible'], edible_parts: ['raíz', 'hoja'], notes: 'Andina. Crece bien en suelos sueltos y bien drenados.', companions: ['frijol'], clash: [] },
  achira:         { e: '🌿', n: 'Achira',         sci: 'Canna edulis',                                    sp: 1,    sun: 'completo', zn: [2, 3],     type: 'herbaceo',    origin: 'native',   functions: ['comestible'], edible_parts: ['raíz'], notes: 'Almidón andino histórico. Muy ornamental en flor.', companions: [], clash: [] },
  oca:            { e: '🟠', n: 'Oca',            sci: 'Oxalis tuberosa',                                 sp: 0.4,  sun: 'completo', zn: [3, 4],     type: 'herbaceo',    origin: 'native',   functions: ['comestible'], edible_parts: ['raíz'], notes: 'Tubérculo andino. Tolera heladas suaves. Sabor ácido-dulce.', companions: ['papa', 'quinua'], clash: [] },
  ulluco:         { e: '🟣', n: 'Ulluco',         sci: 'Ullucus tuberosus',     aliases: ['melloco'],   sp: 0.4,  sun: 'completo', zn: [3, 4],     type: 'herbaceo',    origin: 'native',   functions: ['comestible'], edible_parts: ['raíz', 'hoja'], notes: 'Andino. Hojas comestibles como espinaca.', companions: ['papa', 'oca'], clash: [] },
  batata:         { e: '🍠', n: 'Batata',         sci: 'Ipomoea batatas',       aliases: ['camote', 'boniato'], sp: 0.8, sun: 'completo', zn: [2, 3, 4], type: 'cobertura', origin: 'native', functions: ['comestible'], edible_parts: ['raíz', 'hoja'], notes: 'Cobertura comestible bajo frutales. Hojas también comestibles.', companions: ['platano', 'maiz'], clash: [] },

  // ---- Aromáticas / medicinales ----
  toronjil:       { e: '🌿', n: 'Toronjil',       sci: 'Melissa officinalis',   aliases: ['melisa'],    sp: 0.4,  sun: 'parcial',  zn: [1, 2],     type: 'herbaceo',    origin: 'adapted',  functions: ['medicinal', 'polinizador'], edible_parts: ['hoja'], notes: 'Té calmante. Atrae abejas. Auto-siembra moderada.', companions: ['cafe'], clash: [] },
  hinojo:         { e: '🌱', n: 'Hinojo',         sci: 'Foeniculum vulgare',                              sp: 0.8,  sun: 'completo', zn: [1, 2],     type: 'herbaceo',    origin: 'adapted',  functions: ['comestible', 'medicinal', 'polinizador'], edible_parts: ['hoja', 'semilla', 'bulbo'], notes: 'Atrae avispas parasíticas que controlan plagas. Alelopático con muchas hortalizas.', companions: [], clash: ['frijol', 'tomate'] },
  oregano:        { e: '🌿', n: 'Orégano',        sci: 'Origanum vulgare',                                sp: 0.5,  sun: 'completo', zn: [1, 2],     type: 'arbusto',     origin: 'adapted',  functions: ['comestible', 'medicinal', 'polinizador'], edible_parts: ['hoja'], notes: 'Repele insectos. Borde aromático perenne.', companions: ['frijol'], clash: [] },
  albahaca:       { e: '🌱', n: 'Albahaca',       sci: 'Ocimum basilicum',                                sp: 0.4,  sun: 'completo', zn: [1, 2],     type: 'herbaceo',    origin: 'adapted',  functions: ['comestible', 'medicinal', 'polinizador'], edible_parts: ['hoja'], notes: 'Compañera clásica del tomate. Repele moscas y mosquitos.', companions: ['tomate'], clash: ['ruda'] },
  tomillo:        { e: '🌿', n: 'Tomillo',        sci: 'Thymus vulgaris',                                 sp: 0.3,  sun: 'completo', zn: [1, 2],     type: 'arbusto',     origin: 'adapted',  functions: ['medicinal', 'comestible'], edible_parts: ['hoja'], notes: 'Cobertura aromática. Tolera sequía. Borde de huerta.', companions: ['cebolla'], clash: [] },
  lavanda:        { e: '💜', n: 'Lavanda',        sci: 'Lavandula angustifolia',                          sp: 0.6,  sun: 'completo', zn: [2],        type: 'arbusto',     origin: 'adapted',  functions: ['medicinal', 'polinizador'], edible_parts: ['flor'], notes: 'Atrae polinizadores. Borde decorativo y aromático.', companions: ['romero'], clash: [] },
  citronela:      { e: '🌿', n: 'Citronela',      sci: 'Cymbopogon nardus',                               sp: 0.8,  sun: 'completo', zn: [2, 3],     type: 'herbaceo',    origin: 'adapted',  functions: ['medicinal', 'repelente'], edible_parts: [], notes: 'Repele mosquitos. Borde de huerta y entrada.', companions: [], clash: [] },
  yerba_mate:     { e: '🍵', n: 'Yerba mate',     sci: 'Ilex paraguariensis',                             sp: 5,    sun: 'parcial',  zn: [3, 4],     type: 'arbol-medio', origin: 'native',   functions: ['comestible', 'medicinal'], edible_parts: ['hoja'], notes: 'Sub-bosque del Cono Sur. Toma años en producir.', companions: [], clash: [] },

  // ---- Fijadoras / abonadoras ----
  guandul:        { e: '🟫', n: 'Gandul',         sci: 'Cajanus cajan',         aliases: ['frijol de palo'], sp: 1.5, sun: 'completo', zn: [2, 3, 4], type: 'arbusto', origin: 'adapted', functions: ['comestible', 'fija-n'], edible_parts: ['semilla'], notes: 'Fija nitrógeno. Cortavientos productivo. Granos secos para comida.', companions: ['maiz'], clash: [] },
  leucaena:       { e: '🌳', n: 'Leucaena',       sci: 'Leucaena leucocephala',                           sp: 6,    sun: 'completo', zn: [2, 3, 4],  type: 'arbol-medio', origin: 'adapted',  functions: ['fija-n', 'forraje'], edible_parts: [], notes: 'Fija nitrógeno; rápida; biomasa alta. Puede ser invasora — controla rebrotes.', companions: ['cafe'], clash: [] },
  matarraton:     { e: '🌳', n: 'Matarratón',     sci: 'Gliricidia sepium',                               sp: 5,    sun: 'completo', zn: [2, 3, 4],  type: 'arbol-medio', origin: 'native',   functions: ['fija-n', 'cerca-viva', 'forraje'], edible_parts: [], notes: 'Cerca viva clásica. Estacas enraizan fácil. Flores comestibles.', companions: ['cafe', 'cacao'], clash: [] },
  habas:          { e: '🟢', n: 'Habas',          sci: 'Vicia faba',                                       sp: 0.4,  sun: 'completo', zn: [2, 3],     type: 'herbaceo',    origin: 'adapted',  functions: ['comestible', 'fija-n'], edible_parts: ['semilla', 'vaina'], notes: 'Andina. Tolera frescas. Excelente para rotación.', companions: ['maiz', 'papa'], clash: [] },
  alfalfa:        { e: '🌿', n: 'Alfalfa',        sci: 'Medicago sativa',                                  sp: 0.4,  sun: 'completo', zn: [2, 3],     type: 'cobertura',   origin: 'adapted',  functions: ['fija-n', 'forraje'], edible_parts: ['hoja'], notes: 'Cobertura fijadora de N. Forraje de alta calidad.', companions: [], clash: [] },
  tagetes:        { e: '🌼', n: 'Tagete',         sci: 'Tagetes erecta',        aliases: ['copetillo', 'cempasúchil'], sp: 0.5, sun: 'completo', zn: [1, 2], type: 'herbaceo', origin: 'native', functions: ['polinizador', 'biocida'], edible_parts: ['flor'], notes: 'Repele nematodos del suelo. Compañera clásica de hortalizas.', companions: ['tomate', 'frijol'], clash: [] },

  // ---- Granos / cereales adicionales ----
  arroz:          { e: '🍚', n: 'Arroz',          sci: 'Oryza sativa',                                     sp: 0.3,  sun: 'completo', zn: [3, 4],     type: 'herbaceo',    origin: 'adapted',  functions: ['comestible'], edible_parts: ['semilla'], notes: 'Necesita inundación o saturación de suelo. Producción intensiva.', companions: [], clash: [] },
  sorgo:          { e: '🌾', n: 'Sorgo',          sci: 'Sorghum bicolor',                                  sp: 0.4,  sun: 'completo', zn: [2, 3],     type: 'herbaceo',    origin: 'adapted',  functions: ['comestible', 'forraje'], edible_parts: ['semilla'], notes: 'Tolera sequía mejor que el maíz. Doble propósito grano + forraje.', companions: ['frijol'], clash: [] }
};

export const PDB_GLYPH_FALLBACK = 'Seed';
