#!/usr/bin/env python3
"""
Build the canonical plant catalog (src/lib/pfaf/pfafDb.json).

Free taxonomic APIs (Wikidata/GBIF) don't supply clean PFAF-style ecology
(hardiness zone, edible/medicinal/other ratings, moisture, soil), and `hard`
drives the engine's eligibility filter — wrong values break recommendations.
So this is a *curated* dataset: real, well-known useful species grouped by
climate/use category. Each category supplies ecologically-correct defaults;
per-species overrides refine them. Run:  python scripts/build_plant_db.py
"""
import json, os, re

# ── Field order matches PfafEntry (src/lib/pfaf/pfafPool.ts) ──
# defaults per category: type, space(m), sun, water, soil, hard(min USDA zone),
# edible, med, other, hab, regions, origin
SUN_FULL = "Pleno sol"
SUN_PART = "Sol o sombra parcial"
SUN_SHADE = "Sombra parcial"

CATEGORIES: dict[str, dict] = {
    "temperate_fruit": dict(type="Árbol", space=5, sun=SUN_FULL, water="Media", soil="Ligero",
        hard=4, edible=5, med=2, other=1, hab="Huerto", regions=["temperate", "nordic"], origin="adapted"),
    "temperate_nut": dict(type="Árbol", space=8, sun=SUN_FULL, water="Media", soil="Ligero",
        hard=5, edible=5, med=1, other=2, hab="Bosque comestible", regions=["temperate", "nordic"], origin="adapted"),
    "berry_shrub": dict(type="Arbusto", space=1.2, sun=SUN_PART, water="Media", soil="Rico",
        hard=4, edible=5, med=2, other=1, hab="Borde", regions=["temperate", "nordic"], origin="native"),
    "nordic_berry": dict(type="Arbusto", space=0.8, sun=SUN_PART, water="Media", soil="Ácido",
        hard=2, edible=4, med=2, other=1, hab="Bosque nórdico", regions=["nordic"], origin="native"),
    "mediterranean": dict(type="Árbol", space=5, sun=SUN_FULL, water="Baja", soil="Drenado",
        hard=8, edible=5, med=2, other=1, hab="Huerto mediterráneo", regions=["mediterranean"], origin="native"),
    "med_herb": dict(type="Arbusto", space=0.6, sun=SUN_FULL, water="Baja", soil="Seco / Drenado",
        hard=7, edible=3, med=4, other=2, hab="Borde aromático", regions=["mediterranean"], origin="native"),
    "subtropical": dict(type="Árbol", space=5, sun=SUN_FULL, water="Media", soil="Ligero",
        hard=9, edible=5, med=2, other=1, hab="Huerto subtropical", regions=["subtropical", "mediterranean"], origin="adapted"),
    "tropical_fruit": dict(type="Árbol", space=8, sun=SUN_FULL, water="Media", soil="Rico",
        hard=10, edible=5, med=2, other=1, hab="Bosque tropical", regions=["tropical"], origin="adapted"),
    "tropical_understory": dict(type="Arbusto", space=2.5, sun=SUN_SHADE, water="Alta", soil="Rico",
        hard=10, edible=4, med=2, other=1, hab="Sotobosque tropical", regions=["tropical"], origin="adapted"),
    "tropical_staple": dict(type="Hierba", space=1.0, sun=SUN_FULL, water="Media", soil="Ligero",
        hard=10, edible=5, med=1, other=1, hab="Cultivo", regions=["tropical", "mesoamerica"], origin="native"),
    "nfixer_tree": dict(type="Árbol", space=8, sun=SUN_FULL, water="Media", soil="Ligero",
        hard=8, edible=2, med=1, other=5, hab="Fijador de nitrógeno", regions=["tropical", "subtropical"], origin="native"),
    "nfixer_temp": dict(type="Arbusto", space=3, sun=SUN_FULL, water="Baja", soil="Pobre",
        hard=3, edible=1, med=1, other=5, hab="Fijador de nitrógeno", regions=["temperate", "nordic"], origin="adapted"),
    "veg_annual": dict(type="Hierba", space=0.4, sun=SUN_FULL, water="Media", soil="Rico",
        hard=3, edible=5, med=1, other=1, hab="Cultivo", regions=["temperate", "mediterranean", "subtropical"], origin="adapted", annual=True),
    "root_annual": dict(type="Raíz", space=0.2, sun=SUN_FULL, water="Media", soil="Suelto",
        hard=3, edible=5, med=1, other=1, hab="Cultivo", regions=["temperate", "nordic"], origin="adapted", annual=True),
    "leafy": dict(type="Hierba", space=0.3, sun=SUN_PART, water="Media", soil="Rico",
        hard=4, edible=5, med=1, other=1, hab="Cultivo", regions=["temperate", "nordic", "mediterranean"], origin="adapted", annual=True),
    "culinary_herb": dict(type="Hierba", space=0.3, sun=SUN_FULL, water="Media", soil="Ligero",
        hard=6, edible=4, med=3, other=2, hab="Huerto de hierbas", regions=["mediterranean", "temperate"], origin="adapted"),
    "medicinal_herb": dict(type="Hierba perenne", space=0.4, sun=SUN_PART, water="Media", soil="Rico",
        hard=4, edible=2, med=5, other=2, hab="Jardín medicinal", regions=["temperate", "nordic"], origin="native"),
    "accumulator": dict(type="Hierba perenne", space=0.5, sun=SUN_PART, water="Media", soil="Rico",
        hard=3, edible=2, med=3, other=5, hab="Acumulador dinámico", regions=["temperate", "nordic"], origin="native"),
    "cover_crop": dict(type="Hierba", space=0.2, sun=SUN_FULL, water="Media", soil="Cualquiera",
        hard=3, edible=2, med=1, other=4, hab="Abono verde", regions=["temperate", "mediterranean"], origin="adapted", annual=True),
    "grain": dict(type="Hierba alta", space=0.3, sun=SUN_FULL, water="Media", soil="Cualquiera",
        hard=4, edible=5, med=1, other=2, hab="Cultivo mayor", regions=["temperate", "nordic"], origin="adapted", annual=True),
    "andean": dict(type="Hierba", space=0.4, sun=SUN_FULL, water="Baja", soil="Pobre",
        hard=5, edible=5, med=1, other=1, hab="Andino", regions=["andes"], origin="native"),
    "vine_fruit": dict(type="Enredadera", space=2, sun=SUN_FULL, water="Media", soil="Drenado",
        hard=6, edible=5, med=1, other=1, hab="Pérgola", regions=["temperate", "mediterranean"], origin="native"),
    "useful_tree": dict(type="Árbol", space=8, sun=SUN_FULL, water="Media", soil="Cualquiera",
        hard=5, edible=1, med=2, other=5, hab="Multipropósito", regions=["temperate"], origin="native"),
    "palm": dict(type="Árbol", space=6, sun=SUN_FULL, water="Media", soil="Drenado",
        hard=10, edible=5, med=1, other=2, hab="Trópico", regions=["tropical", "subtropical"], origin="native"),
}

# Each species: (n_es, sci, family) or (n_es, sci, family, {overrides})
SPECIES: dict[str, list] = {
    "temperate_fruit": [
        ("Membrillo", "Cydonia oblonga", "Rosaceae"),
        ("Cerezo", "Prunus avium", "Rosaceae", {"hard": 3}),
        ("Cerezo ácido", "Prunus cerasus", "Rosaceae", {"hard": 3}),
        ("Durazno", "Prunus persica", "Rosaceae", {"hard": 5, "regions": ["temperate", "mediterranean"]}),
        ("Damasco", "Prunus armeniaca", "Rosaceae", {"hard": 5}),
        ("Níspero europeo", "Mespilus germanica", "Rosaceae"),
        ("Serbal", "Sorbus aucuparia", "Rosaceae", {"hard": 3, "edible": 3, "regions": ["nordic", "temperate"]}),
        ("Endrino", "Prunus spinosa", "Rosaceae", {"type": "Arbusto", "space": 3, "edible": 3, "other": 3}),
        ("Morera blanca", "Morus alba", "Moraceae", {"hard": 5}),
        ("Morera negra", "Morus nigra", "Moraceae", {"hard": 6}),
        ("Caqui", "Diospyros kaki", "Ebenaceae", {"hard": 7}),
        ("Asimina", "Asimina triloba", "Annonaceae", {"hard": 5, "regions": ["temperate"]}),
        ("Guinda", "Prunus subg. Cerasus", "Rosaceae", {"hard": 4}),
        ("Manzano silvestre", "Malus sylvestris", "Rosaceae", {"edible": 3, "origin": "native"}),
        ("Almez", "Celtis australis", "Cannabaceae", {"hard": 7, "edible": 3, "other": 3}),
    ],
    "temperate_nut": [
        ("Nogal", "Juglans regia", "Juglandaceae", {"space": 12, "hard": 5}),
        ("Nogal negro", "Juglans nigra", "Juglandaceae", {"space": 14, "hard": 4}),
        ("Castaño", "Castanea sativa", "Fagaceae", {"space": 12, "hard": 5}),
        ("Almendro", "Prunus dulcis", "Rosaceae", {"space": 6, "hard": 7, "water": "Baja", "regions": ["mediterranean"]}),
        ("Pacana", "Carya illinoinensis", "Juglandaceae", {"space": 14, "hard": 6}),
        ("Piñonero", "Pinus pinea", "Pinaceae", {"space": 8, "hard": 7, "regions": ["mediterranean"]}),
        ("Roble", "Quercus robur", "Fagaceae", {"space": 14, "edible": 2, "other": 4, "hab": "Dosel"}),
        ("Castaño de agua", "Eleocharis dulcis", "Cyperaceae", {"type": "Hierba", "space": 0.3, "hard": 9, "water": "Alta", "hab": "Cerca de agua"}),
    ],
    "berry_shrub": [
        ("Zarzamora", "Rubus fruticosus", "Rosaceae", {"space": 2}),
        ("Arándano azul", "Vaccinium corymbosum", "Ericaceae", {"soil": "Ácido", "hard": 3}),
        ("Grosella roja", "Ribes rubrum", "Grossulariaceae", {"hard": 3}),
        ("Grosella espinosa", "Ribes uva-crispa", "Grossulariaceae", {"hard": 3}),
        ("Saúco", "Sambucus nigra", "Adoxaceae", {"space": 4, "med": 4}),
        ("Aronia", "Aronia melanocarpa", "Rosaceae", {"med": 3}),
        ("Madreselva comestible", "Lonicera caerulea", "Caprifoliaceae", {"hard": 2}),
        ("Goji", "Lycium barbarum", "Solanaceae", {"med": 4, "regions": ["temperate", "subtropical"]}),
        ("Espino amarillo", "Hippophae rhamnoides", "Elaeagnaceae", {"space": 3, "med": 4, "other": 4, "hab": "Fijador de nitrógeno"}),
        ("Cornejo", "Cornus mas", "Cornaceae", {"space": 4, "edible": 4}),
        ("Membrillero japonés", "Chaenomeles japonica", "Rosaceae", {"edible": 3}),
        ("Frutilla / Fresa", "Fragaria × ananassa", "Rosaceae", {"type": "Hierba", "space": 0.3, "hab": "Cobertura"}),
        ("Fresa silvestre", "Fragaria vesca", "Rosaceae", {"type": "Hierba", "space": 0.2, "hab": "Cobertura"}),
    ],
    "nordic_berry": [
        ("Arándano rojo americano", "Vaccinium macrocarpon", "Ericaceae", {"type": "Hierba", "space": 0.4, "hab": "Cobertura ácida"}),
        ("Mora de los pantanos", "Rubus chamaemorus", "Rosaceae", {"type": "Hierba", "space": 0.4}),
        ("Camemoro", "Empetrum nigrum", "Ericaceae", {"space": 0.5, "edible": 3}),
        ("Gayuba", "Arctostaphylos uva-ursi", "Ericaceae", {"space": 0.5, "edible": 3, "med": 4, "hab": "Cobertura"}),
    ],
    "mediterranean": [
        ("Granado", "Punica granatum", "Lythraceae", {"space": 4, "hard": 8}),
        ("Algarrobo", "Ceratonia siliqua", "Fabaceae", {"space": 8, "other": 4, "hab": "Fijador de nitrógeno"}),
        ("Níspero japonés", "Eriobotrya japonica", "Rosaceae", {"hard": 8}),
        ("Azufaifo", "Ziziphus jujuba", "Rhamnaceae", {"space": 5, "hard": 7, "med": 3}),
        ("Madroño", "Arbutus unedo", "Ericaceae", {"space": 4, "edible": 4, "origin": "native"}),
        ("Laurel", "Laurus nobilis", "Lauraceae", {"space": 4, "edible": 3, "med": 3, "hab": "Borde aromático"}),
        ("Alcaparra", "Capparis spinosa", "Capparaceae", {"type": "Arbusto", "space": 1, "edible": 4, "hab": "Muro seco"}),
        ("Pistacho", "Pistacia vera", "Anacardiaceae", {"space": 6, "hard": 8}),
    ],
    "med_herb": [
        ("Tomillo", "Thymus vulgaris", "Lamiaceae", {"space": 0.3}),
        ("Salvia", "Salvia officinalis", "Lamiaceae", {"space": 0.6}),
        ("Orégano", "Origanum vulgare", "Lamiaceae", {"type": "Hierba perenne", "space": 0.4, "hard": 5}),
        ("Lavanda", "Lavandula angustifolia", "Lamiaceae", {"space": 0.6, "edible": 2, "other": 3, "hab": "Polinizador"}),
        ("Mejorana", "Origanum majorana", "Lamiaceae", {"type": "Hierba", "space": 0.3}),
        ("Hinojo", "Foeniculum vulgare", "Apiaceae", {"type": "Hierba perenne", "space": 0.5, "edible": 4}),
        ("Ajedrea", "Satureja montana", "Lamiaceae", {"space": 0.3}),
        ("Ruda", "Ruta graveolens", "Rutaceae", {"space": 0.5, "edible": 1, "med": 4}),
    ],
    "subtropical": [
        ("Limonero", "Citrus limon", "Rutaceae", {"hard": 9}),
        ("Lima", "Citrus aurantiifolia", "Rutaceae", {"hard": 10}),
        ("Mandarino", "Citrus reticulata", "Rutaceae", {"hard": 9}),
        ("Pomelo", "Citrus paradisi", "Rutaceae", {"hard": 9}),
        ("Kumquat", "Citrus japonica", "Rutaceae", {"space": 3, "hard": 9}),
        ("Feijoa", "Acca sellowiana", "Myrtaceae", {"space": 4, "hard": 8, "regions": ["subtropical", "andes"]}),
        ("Chirimoya", "Annona cherimola", "Annonaceae", {"hard": 10, "regions": ["subtropical", "andes"]}),
        ("Aguacate Hass", "Persea americana 'Hass'", "Lauraceae", {"space": 8, "hard": 10, "regions": ["subtropical", "mesoamerica"]}),
        ("Kiwi", "Actinidia deliciosa", "Actinidiaceae", {"type": "Enredadera", "space": 4, "hard": 7, "hab": "Pérgola", "regions": ["subtropical", "temperate"]}),
        ("Macadamia", "Macadamia integrifolia", "Proteaceae", {"hard": 10, "edible": 5}),
        ("Tejocote", "Crataegus mexicana", "Rosaceae", {"space": 5, "hard": 8, "regions": ["mesoamerica", "subtropical"]}),
    ],
    "tropical_fruit": [
        ("Guayaba", "Psidium guajava", "Myrtaceae", {"space": 5, "regions": ["tropical", "mesoamerica"], "origin": "native"}),
        ("Guanábana", "Annona muricata", "Annonaceae", {"space": 6, "med": 3, "regions": ["tropical", "mesoamerica"], "origin": "native"}),
        ("Maracuyá", "Passiflora edulis", "Passifloraceae", {"type": "Enredadera", "space": 3, "hab": "Pérgola tropical", "origin": "native"}),
        ("Lichi", "Litchi chinensis", "Sapindaceae", {"space": 8}),
        ("Longan", "Dimocarpus longan", "Sapindaceae", {"space": 8}),
        ("Rambután", "Nephelium lappaceum", "Sapindaceae", {"space": 8}),
        ("Carambola", "Averrhoa carambola", "Oxalidaceae", {"space": 6}),
        ("Yaca", "Artocarpus heterophyllus", "Moraceae", {"space": 12}),
        ("Árbol del pan", "Artocarpus altilis", "Moraceae", {"space": 12}),
        ("Mangostán", "Garcinia mangostana", "Clusiaceae", {"space": 8, "sun": SUN_SHADE}),
        ("Tamarindo", "Tamarindus indica", "Fabaceae", {"space": 10, "other": 4, "hab": "Fijador de nitrógeno"}),
        ("Zapote mamey", "Pouteria sapota", "Sapotaceae", {"space": 10, "regions": ["tropical", "mesoamerica"], "origin": "native"}),
        ("Chicozapote", "Manilkara zapota", "Sapotaceae", {"space": 10, "regions": ["tropical", "mesoamerica"], "origin": "native"}),
        ("Noni", "Morinda citrifolia", "Rubiaceae", {"space": 4, "edible": 3, "med": 4}),
        ("Pitahaya", "Hylocereus undatus", "Cactaceae", {"type": "Enredadera", "space": 2, "water": "Baja", "hab": "Cactus trepador", "regions": ["tropical", "mesoamerica"], "origin": "native"}),
        ("Acerola", "Malpighia emarginata", "Malpighiaceae", {"space": 4, "med": 3, "regions": ["tropical", "mesoamerica"], "origin": "native"}),
        ("Marañón / Anacardo", "Anacardium occidentale", "Anacardiaceae", {"space": 8, "regions": ["tropical"], "origin": "native"}),
        ("Caimito", "Chrysophyllum cainito", "Sapotaceae", {"space": 10, "regions": ["tropical", "mesoamerica"], "origin": "native"}),
        ("Borojó", "Alibertia patinoi", "Rubiaceae", {"space": 5, "regions": ["tropical", "andes"], "origin": "native"}),
        ("Cocona", "Solanum sessiliflorum", "Solanaceae", {"type": "Arbusto", "space": 1.5, "regions": ["tropical", "andes"], "origin": "native"}),
    ],
    "tropical_understory": [
        ("Cardamomo", "Elettaria cardamomum", "Zingiberaceae", {"type": "Hierba perenne", "space": 1.5, "med": 3}),
        ("Pimienta negra", "Piper nigrum", "Piperaceae", {"type": "Enredadera", "space": 1.5, "med": 3}),
        ("Vainilla", "Vanilla planifolia", "Orchidaceae", {"type": "Enredadera", "space": 1, "hab": "Orquídea trepadora"}),
        ("Achiote", "Bixa orellana", "Bixaceae", {"space": 4, "other": 3, "regions": ["tropical", "mesoamerica"], "origin": "native"}),
        ("Cúrcuma", "Curcuma longa", "Zingiberaceae", {"type": "Hierba", "space": 0.5, "med": 5}),
        ("Jengibre", "Zingiber officinale", "Zingiberaceae", {"type": "Hierba", "space": 0.5, "med": 4}),
    ],
    "tropical_staple": [
        ("Taro / Malanga", "Colocasia esculenta", "Araceae", {"type": "Raíz", "space": 0.6, "water": "Alta", "hab": "Cerca de agua"}),
        ("Camote / Batata", "Ipomoea batatas", "Convolvulaceae", {"type": "Enredadera rastrera", "space": 0.5, "hab": "Cobertura"}),
        ("Ñame", "Dioscorea alata", "Dioscoreaceae", {"type": "Enredadera", "space": 0.5}),
        ("Caña de azúcar", "Saccharum officinarum", "Poaceae", {"type": "Hierba alta", "space": 0.6, "water": "Alta"}),
        ("Piña", "Ananas comosus", "Bromeliaceae", {"type": "Hierba", "space": 0.6, "water": "Baja", "origin": "native"}),
        ("Arroz", "Oryza sativa", "Poaceae", {"type": "Hierba", "space": 0.2, "water": "Alta", "hab": "Arrozal", "annual": True}),
        ("Maní / Cacahuate", "Arachis hypogaea", "Fabaceae", {"type": "Hierba", "space": 0.3, "other": 4, "hab": "Fijador de nitrógeno", "annual": True, "regions": ["tropical", "mesoamerica", "andes"], "origin": "native"}),
        ("Achira", "Canna edulis", "Cannaceae", {"type": "Hierba", "space": 0.6, "regions": ["andes", "tropical"], "origin": "native"}),
    ],
    "nfixer_tree": [
        ("Leucaena", "Leucaena leucocephala", "Fabaceae", {"edible": 2}),
        ("Matarratón", "Gliricidia sepium", "Fabaceae", {"hab": "Fijador / cerca viva", "regions": ["tropical", "mesoamerica"], "origin": "native"}),
        ("Acacia negra", "Acacia mearnsii", "Fabaceae", {"regions": ["subtropical"], "origin": "adapted"}),
        ("Mezquite", "Prosopis pallida", "Fabaceae", {"water": "Baja", "edible": 3, "regions": ["subtropical", "andes"], "origin": "native"}),
        ("Falso índigo", "Amorpha fruticosa", "Fabaceae", {"type": "Arbusto", "space": 2, "hard": 4, "regions": ["temperate"]}),
        ("Aliso", "Alnus glutinosa", "Betulaceae", {"hard": 3, "water": "Alta", "regions": ["temperate", "nordic"], "hab": "Fijador cerca de agua"}),
        ("Algarrobo blanco", "Prosopis alba", "Fabaceae", {"water": "Baja", "edible": 3, "regions": ["subtropical"], "origin": "native"}),
        ("Guaba de bejuco", "Inga vera", "Fabaceae", {"regions": ["tropical", "mesoamerica"], "origin": "native"}),
    ],
    "nfixer_temp": [
        ("Caragana / Guisante siberiano", "Caragana arborescens", "Fabaceae", {"hard": 2, "edible": 3}),
        ("Robinia / Falsa acacia", "Robinia pseudoacacia", "Fabaceae", {"type": "Árbol", "space": 8, "hard": 4, "other": 5}),
        ("Olivo de otoño", "Elaeagnus umbellata", "Elaeagnaceae", {"hard": 4, "edible": 4}),
        ("Trébol blanco", "Trifolium repens", "Fabaceae", {"type": "Hierba", "space": 0.2, "hab": "Cobertura fijadora"}),
        ("Alfalfa", "Medicago sativa", "Fabaceae", {"type": "Hierba", "space": 0.3, "hab": "Abono verde", "other": 4}),
        ("Lupino", "Lupinus albus", "Fabaceae", {"type": "Hierba", "space": 0.3, "edible": 3, "annual": True}),
        ("Veza", "Vicia sativa", "Fabaceae", {"type": "Hierba", "space": 0.2, "hab": "Abono verde", "annual": True}),
        ("Haba", "Vicia faba", "Fabaceae", {"type": "Hierba", "space": 0.3, "edible": 5, "annual": True}),
        ("Guandul / Gandul", "Cajanus cajan", "Fabaceae", {"type": "Arbusto", "space": 1.5, "edible": 4, "hard": 9, "regions": ["tropical", "subtropical"], "origin": "adapted"}),
    ],
    "veg_annual": [
        ("Pepino", "Cucumis sativus", "Cucurbitaceae", {"type": "Enredadera", "space": 0.5}),
        ("Berenjena", "Solanum melongena", "Solanaceae", {"hard": 9, "regions": ["subtropical", "tropical"]}),
        ("Okra", "Abelmoschus esculentus", "Malvaceae", {"hard": 9, "regions": ["tropical", "subtropical"]}),
        ("Melón", "Cucumis melo", "Cucurbitaceae", {"type": "Enredadera rastrera", "space": 1}),
        ("Sandía", "Citrullus lanatus", "Cucurbitaceae", {"type": "Enredadera rastrera", "space": 1.5}),
        ("Chayote", "Sicyos edulis", "Cucurbitaceae", {"type": "Enredadera", "space": 2, "hab": "Pérgola", "regions": ["mesoamerica", "subtropical"], "origin": "native"}),
        ("Guisante / Arveja", "Pisum sativum", "Fabaceae", {"space": 0.2, "other": 3, "hab": "Cultivo fijador"}),
        ("Pepinillo", "Cucumis anguria", "Cucurbitaceae", {"type": "Enredadera", "space": 0.6}),
        ("Calabacín", "Cucurbita pepo var. cylindrica", "Cucurbitaceae", {"space": 1}),
        ("Tomatillo", "Physalis philadelphica", "Solanaceae", {"space": 0.6, "regions": ["mesoamerica"], "origin": "native"}),
        ("Uchuva / Aguaymanto", "Physalis peruviana", "Solanaceae", {"space": 0.6, "med": 2, "regions": ["andes"], "origin": "native"}),
    ],
    "root_annual": [
        ("Rábano", "Raphanus sativus", "Brassicaceae", {"space": 0.1}),
        ("Nabo", "Brassica rapa", "Brassicaceae", {"space": 0.2}),
        ("Colinabo", "Brassica napus var. napobrassica", "Brassicaceae", {"space": 0.3}),
        ("Apionabo", "Apium graveolens var. rapaceum", "Apiaceae", {"space": 0.25}),
        ("Salsifí", "Tragopogon porrifolius", "Asteraceae", {"space": 0.15}),
        ("Jícama", "Pachyrhizus erosus", "Fabaceae", {"space": 0.3, "hard": 9, "regions": ["mesoamerica", "tropical"], "origin": "native"}),
    ],
    "leafy": [
        ("Espinaca", "Spinacia oleracea", "Amaranthaceae", {"space": 0.2}),
        ("Acelga", "Beta vulgaris var. cicla", "Amaranthaceae", {"space": 0.3, "hard": 5}),
        ("Brócoli", "Brassica oleracea var. italica", "Brassicaceae", {"space": 0.5}),
        ("Coliflor", "Brassica oleracea var. botrytis", "Brassicaceae", {"space": 0.5}),
        ("Repollo", "Brassica oleracea var. capitata", "Brassicaceae", {"space": 0.5, "hard": 5}),
        ("Rúcula", "Eruca vesicaria", "Brassicaceae", {"space": 0.2}),
        ("Achicoria", "Cichorium intybus", "Asteraceae", {"type": "Hierba perenne", "space": 0.3, "med": 3, "hard": 4}),
        ("Berro", "Nasturtium officinale", "Brassicaceae", {"space": 0.2, "water": "Alta", "hab": "Cerca de agua"}),
        ("Quelite / Amaranto hoja", "Amaranthus cruentus", "Amaranthaceae", {"type": "Hierba", "space": 0.4, "regions": ["mesoamerica"], "origin": "native"}),
    ],
    "culinary_herb": [
        ("Perejil", "Petroselinum crispum", "Apiaceae", {"med": 2}),
        ("Eneldo", "Anethum graveolens", "Apiaceae", {"annual": True}),
        ("Estragón", "Artemisia dracunculus", "Asteraceae", {"type": "Hierba perenne"}),
        ("Cebollino", "Allium schoenoprasum", "Amaryllidaceae", {"type": "Hierba perenne", "space": 0.2, "hard": 3}),
        ("Romero rastrero", "Salvia rosmarinus 'Prostratus'", "Lamiaceae", {"type": "Arbusto", "space": 0.6, "water": "Baja"}),
        ("Toronjil / Melisa", "Melissa officinalis", "Lamiaceae", {"type": "Hierba perenne", "space": 0.4, "med": 4, "hard": 4}),
        ("Cilantro vietnamita", "Persicaria odorata", "Polygonaceae", {"type": "Hierba perenne", "space": 0.3, "hard": 9}),
        ("Stevia", "Stevia rebaudiana", "Asteraceae", {"type": "Hierba perenne", "space": 0.4, "hard": 9, "regions": ["subtropical", "andes"], "origin": "native"}),
    ],
    "medicinal_herb": [
        ("Manzanilla", "Matricaria chamomilla", "Asteraceae", {"type": "Hierba", "space": 0.2, "annual": True}),
        ("Caléndula", "Calendula officinalis", "Asteraceae", {"type": "Hierba", "space": 0.3, "other": 3, "hab": "Polinizador", "annual": True}),
        ("Equinácea", "Echinacea purpurea", "Asteraceae", {"space": 0.4, "other": 3}),
        ("Milenrama", "Achillea millefolium", "Asteraceae", {"space": 0.4, "other": 4, "hab": "Acumulador"}),
        ("Ortiga", "Urtica dioica", "Urticaceae", {"space": 0.5, "edible": 3, "other": 5, "hab": "Acumulador dinámico"}),
        ("Diente de león", "Taraxacum officinale", "Asteraceae", {"type": "Hierba", "space": 0.2, "edible": 3, "other": 4, "hab": "Acumulador"}),
        ("Valeriana", "Valeriana officinalis", "Caprifoliaceae", {"space": 0.5}),
        ("Hierbabuena", "Mentha × piperita", "Lamiaceae", {"space": 0.4, "edible": 4, "water": "Alta", "hab": "Cerca de agua"}),
        ("Llantén", "Plantago major", "Plantaginaceae", {"type": "Hierba", "space": 0.2, "other": 3, "hab": "Acumulador"}),
        ("Caléndula de campo", "Tagetes erecta", "Asteraceae", {"type": "Hierba", "space": 0.4, "other": 4, "hab": "Repelente / polinizador", "regions": ["mesoamerica"], "origin": "native", "annual": True}),
    ],
    "accumulator": [
        ("Borraja", "Borago officinalis", "Boraginaceae", {"type": "Hierba", "space": 0.4, "edible": 3, "hab": "Polinizador / acumulador", "annual": True}),
        ("Consuelda rusa", "Symphytum × uplandicum", "Boraginaceae", {"space": 0.7}),
        ("Tanaceto", "Tanacetum vulgare", "Asteraceae", {"space": 0.5, "other": 4}),
        ("Acedera", "Rumex acetosa", "Polygonaceae", {"space": 0.3, "edible": 3}),
    ],
    "cover_crop": [
        ("Trébol carmesí", "Trifolium incarnatum", "Fabaceae", {"hab": "Abono verde fijador"}),
        ("Mostaza blanca", "Sinapis alba", "Brassicaceae", {"hab": "Abono verde"}),
        ("Trigo sarraceno / Alforfón", "Fagopyrum esculentum", "Polygonaceae", {"edible": 4, "hab": "Abono verde / polinizador"}),
        ("Facelia", "Phacelia tanacetifolia", "Boraginaceae", {"edible": 1, "other": 5, "hab": "Polinizador"}),
        ("Centeno forrajero", "Secale cereale 'Forage'", "Poaceae", {"hab": "Abono verde"}),
    ],
    "grain": [
        ("Trigo", "Triticum aestivum", "Poaceae"),
        ("Cebada", "Hordeum vulgare", "Poaceae", {"hard": 3}),
        ("Avena", "Avena sativa", "Poaceae", {"hard": 3}),
        ("Sorgo", "Sorghum bicolor", "Poaceae", {"hard": 8, "water": "Baja", "regions": ["subtropical", "tropical"]}),
        ("Mijo", "Pennisetum glaucum", "Poaceae", {"hard": 9, "water": "Baja", "regions": ["subtropical", "tropical"]}),
        ("Amaranto grano", "Amaranthus caudatus", "Amaranthaceae", {"type": "Hierba", "space": 0.5, "regions": ["andes", "mesoamerica"], "origin": "native"}),
    ],
    "andean": [
        ("Oca", "Oxalis tuberosa", "Oxalidaceae", {"type": "Raíz", "space": 0.3}),
        ("Ulluco / Melloco", "Ullucus tuberosus", "Basellaceae", {"type": "Raíz", "space": 0.3}),
        ("Mashua", "Tropaeolum tuberosum", "Tropaeolaceae", {"type": "Enredadera", "space": 0.4}),
        ("Maca", "Lepidium meyenii", "Brassicaceae", {"type": "Raíz", "space": 0.2, "med": 4, "hard": 6}),
        ("Tarwi / Chocho", "Lupinus mutabilis", "Fabaceae", {"type": "Hierba", "space": 0.4, "other": 4, "hab": "Fijador de nitrógeno"}),
        ("Yacón", "Smallanthus sonchifolius", "Asteraceae", {"type": "Raíz", "space": 0.6, "edible": 4}),
        ("Kiwicha", "Amaranthus caudatus", "Amaranthaceae", {"type": "Hierba", "space": 0.5}),
        ("Cañihua", "Chenopodium pallidicaule", "Amaranthaceae", {"type": "Hierba", "space": 0.4}),
        ("Tomate de árbol", "Solanum betaceum", "Solanaceae", {"type": "Árbol", "space": 3, "hard": 9, "edible": 5}),
        ("Lúcuma", "Pouteria lucuma", "Sapotaceae", {"type": "Árbol", "space": 8, "hard": 9}),
    ],
    "vine_fruit": [
        ("Lúpulo", "Humulus lupulus", "Cannabaceae", {"space": 3, "edible": 2, "med": 3, "other": 3, "hab": "Pérgola"}),
        ("Parra silvestre", "Vitis labrusca", "Vitaceae", {"hard": 5}),
        ("Kiwi ártico", "Actinidia arguta", "Actinidiaceae", {"space": 4, "hard": 4}),
        ("Akebia", "Akebia quinata", "Lardizabalaceae", {"space": 3, "hard": 5, "edible": 3}),
        ("Granadilla", "Passiflora ligularis", "Passifloraceae", {"space": 3, "hard": 9, "regions": ["andes", "tropical"], "origin": "native"}),
    ],
    "useful_tree": [
        ("Sauce", "Salix alba", "Salicaceae", {"space": 8, "med": 3, "water": "Alta", "hab": "Cerca de agua / cestería"}),
        ("Álamo", "Populus nigra", "Salicaceae", {"space": 10, "water": "Alta", "hab": "Cortaviento"}),
        ("Bambú", "Phyllostachys edulis", "Poaceae", {"type": "Hierba alta", "space": 3, "edible": 3, "other": 5, "hab": "Construcción", "hard": 7}),
        ("Tilo", "Tilia cordata", "Malvaceae", {"space": 12, "edible": 2, "med": 3, "other": 3, "hab": "Polinizador"}),
        ("Moringa", "Moringa oleifera", "Moringaceae", {"space": 4, "edible": 4, "med": 4, "other": 3, "hard": 10, "regions": ["tropical", "subtropical"], "origin": "adapted"}),
        ("Abedul", "Betula pendula", "Betulaceae", {"space": 8, "edible": 2, "med": 3, "hard": 2, "regions": ["nordic", "temperate"]}),
        ("Ginkgo", "Ginkgo biloba", "Ginkgoaceae", {"space": 10, "edible": 3, "med": 4, "hard": 4}),
        ("Paulownia", "Paulownia tomentosa", "Paulowniaceae", {"space": 10, "edible": 1, "other": 5, "hab": "Madera rápida", "hard": 6}),
    ],
    "palm": [
        ("Coco", "Cocos nucifera", "Arecaceae", {"space": 8, "hard": 11}),
        ("Dátil", "Phoenix dactylifera", "Arecaceae", {"space": 8, "water": "Baja", "hard": 9, "regions": ["mediterranean", "subtropical"]}),
        ("Palma de durazno / Pejibaye", "Bactris gasipaes", "Arecaceae", {"space": 6, "regions": ["tropical", "mesoamerica"], "origin": "native"}),
        ("Açaí", "Euterpe oleracea", "Arecaceae", {"space": 5, "water": "Alta", "regions": ["tropical"], "origin": "native"}),
        ("Aguaje / Moriche", "Mauritia flexuosa", "Arecaceae", {"space": 8, "water": "Alta", "hab": "Humedal tropical", "regions": ["tropical"], "origin": "native"}),
        ("Palma aceitera", "Elaeis guineensis", "Arecaceae", {"space": 8, "other": 3}),
    ],
}


# ── Second batch: new categories ──
CATEGORIES.update({
    "aquatic": dict(type="Hierba", space=0.5, sun=SUN_FULL, water="Alta", soil="Rico",
        hard=5, edible=4, med=1, other=2, hab="Humedal / cerca de agua", regions=["temperate", "subtropical"], origin="native"),
    "tropical_veg": dict(type="Enredadera", space=1.0, sun=SUN_FULL, water="Media", soil="Rico",
        hard=10, edible=5, med=1, other=1, hab="Cultivo tropical", regions=["tropical", "subtropical"], origin="adapted", annual=True),
    "legume_grain": dict(type="Hierba", space=0.3, sun=SUN_FULL, water="Media", soil="Ligero",
        hard=5, edible=5, med=1, other=4, hab="Cultivo fijador", regions=["temperate", "mediterranean"], origin="adapted", annual=True),
    "fiber_dye": dict(type="Hierba alta", space=0.5, sun=SUN_FULL, water="Media", soil="Ligero",
        hard=7, edible=1, med=2, other=5, hab="Fibra / tinte", regions=["subtropical", "temperate"], origin="adapted"),
})

SPECIES_EXTRA: dict[str, list] = {
    "temperate_fruit": [
        ("Nectarina", "Prunus persica var. nucipersica", "Rosaceae", {"hard": 5}),
        ("Ciruela mirabel", "Prunus domestica subsp. syriaca", "Rosaceae"),
        ("Saskatoon", "Amelanchier alnifolia", "Rosaceae", {"type": "Arbusto", "space": 3, "edible": 4, "hard": 2}),
        ("Espino albar", "Crataegus monogyna", "Rosaceae", {"space": 5, "edible": 3, "med": 3}),
        ("Rosa rugosa", "Rosa rugosa", "Rosaceae", {"type": "Arbusto", "space": 1.5, "edible": 3, "med": 3, "hab": "Borde / escaramujo"}),
        ("Búfalo de las praderas", "Shepherdia argentea", "Elaeagnaceae", {"type": "Arbusto", "space": 3, "edible": 3, "other": 4, "hab": "Fijador de nitrógeno"}),
        ("Cerezo de Nanking", "Prunus tomentosa", "Rosaceae", {"type": "Arbusto", "space": 2, "hard": 3}),
        ("Membrillero de China", "Pseudocydonia sinensis", "Rosaceae", {"edible": 3}),
        ("Avellano turco", "Corylus colurna", "Betulaceae", {"space": 10, "edible": 5, "other": 2}),
        ("Cornalina", "Cornus officinalis", "Cornaceae", {"space": 5, "edible": 3, "med": 4}),
    ],
    "temperate_nut": [
        ("Nuez de Manchuria", "Juglans mandshurica", "Juglandaceae", {"space": 12, "hard": 3}),
        ("Nuez gris", "Juglans cinerea", "Juglandaceae", {"space": 12, "hard": 3}),
        ("Nuez de hicoria", "Carya ovata", "Juglandaceae", {"space": 14, "hard": 4}),
        ("Haya", "Fagus sylvatica", "Fagaceae", {"space": 14, "edible": 3, "other": 3, "hab": "Dosel"}),
        ("Araucaria / Piñonero andino", "Araucaria araucana", "Araucariaceae", {"space": 10, "hard": 7, "regions": ["andes", "temperate"], "origin": "native"}),
        ("Castaño chino", "Castanea mollissima", "Fagaceae", {"space": 12, "hard": 5}),
        ("Alfóncigo silvestre", "Pistacia atlantica", "Anacardiaceae", {"space": 8, "water": "Baja", "hard": 8, "regions": ["mediterranean"]}),
    ],
    "berry_shrub": [
        ("Tayberry", "Rubus 'Tayberry'", "Rosaceae", {"space": 2}),
        ("Boysenberry", "Rubus ursinus × idaeus", "Rosaceae", {"space": 2}),
        ("Frambuesa negra", "Rubus occidentalis", "Rosaceae", {"space": 1.5}),
        ("Salmonberry", "Rubus spectabilis", "Rosaceae", {"space": 2, "edible": 3}),
        ("Arándano rojo de monte", "Vaccinium myrtillus", "Ericaceae", {"space": 0.5, "soil": "Ácido", "hard": 3, "med": 3}),
        ("Jostaberry", "Ribes × nidigrolaria", "Grossulariaceae", {"hard": 3}),
        ("Grosella dorada", "Ribes aureum", "Grossulariaceae", {"hard": 3, "edible": 4}),
        ("Casís alpino", "Ribes alpinum", "Grossulariaceae", {"edible": 2, "other": 2, "hab": "Seto"}),
        ("Baya de miel azul", "Lonicera kamtschatica", "Caprifoliaceae", {"hard": 2}),
        ("Chokeberry roja", "Aronia arbutifolia", "Rosaceae", {"med": 3}),
    ],
    "nordic_berry": [
        ("Mora ártica", "Rubus arcticus", "Rosaceae", {"type": "Hierba", "space": 0.3}),
        ("Arándano pantanoso", "Vaccinium uliginosum", "Ericaceae", {"space": 0.6}),
        ("Frutilla nórdica", "Fragaria virginiana", "Rosaceae", {"type": "Hierba", "space": 0.3, "hab": "Cobertura"}),
    ],
    "mediterranean": [
        ("Mirto", "Myrtus communis", "Myrtaceae", {"type": "Arbusto", "space": 2, "edible": 3, "med": 3}),
        ("Lentisco", "Pistacia lentiscus", "Anacardiaceae", {"type": "Arbusto", "space": 3, "edible": 2, "med": 3, "other": 3}),
        ("Acebuche", "Olea europaea var. sylvestris", "Oleaceae", {"space": 6, "water": "Baja", "edible": 3}),
        ("Serbal silvestre", "Sorbus domestica", "Rosaceae", {"space": 8, "edible": 3}),
        ("Granado enano", "Punica granatum 'Nana'", "Lythraceae", {"type": "Arbusto", "space": 1.5}),
        ("Cornicabra", "Pistacia terebinthus", "Anacardiaceae", {"type": "Arbusto", "space": 4, "edible": 2, "other": 3}),
    ],
    "med_herb": [
        ("Hisopo", "Hyssopus officinalis", "Lamiaceae", {"space": 0.4}),
        ("Cedrón / Hierba luisa", "Aloysia citrodora", "Verbenaceae", {"type": "Arbusto", "space": 1.5, "med": 3}),
        ("Ajenjo", "Artemisia absinthium", "Asteraceae", {"type": "Hierba perenne", "space": 0.6, "edible": 1, "med": 4, "other": 3}),
        ("Hierba santa", "Salvia sclarea", "Lamiaceae", {"space": 0.6}),
        ("Albahaca morada", "Ocimum basilicum 'Purpurascens'", "Lamiaceae", {"type": "Hierba", "space": 0.3, "annual": True}),
        ("Lavandín", "Lavandula × intermedia", "Lamiaceae", {"space": 0.7, "edible": 1, "other": 3, "hab": "Polinizador"}),
    ],
    "subtropical": [
        ("Zapote blanco", "Casimiroa edulis", "Rutaceae", {"space": 8, "hard": 9, "regions": ["mesoamerica", "subtropical"], "origin": "native"}),
        ("Atemoya", "Annona × atemoya", "Annonaceae", {"space": 6, "hard": 10}),
        ("Anón / Saramuyo", "Annona squamosa", "Annonaceae", {"space": 5, "hard": 10, "regions": ["tropical", "mesoamerica"], "origin": "native"}),
        ("Naranja agria", "Citrus × aurantium", "Rutaceae", {"hard": 9, "med": 2}),
        ("Cidra", "Citrus medica", "Rutaceae", {"space": 3, "hard": 10}),
        ("Yuzu", "Citrus junos", "Rutaceae", {"hard": 8}),
        ("Bergamota", "Citrus bergamia", "Rutaceae", {"hard": 9, "med": 2}),
        ("Mano de Buda", "Citrus medica var. sarcodactylis", "Rutaceae", {"space": 3, "hard": 10}),
        ("Plinia / Jaboticaba", "Plinia cauliflora", "Myrtaceae", {"space": 6, "hard": 9, "regions": ["subtropical", "tropical"], "origin": "native"}),
        ("Guayaba fresa", "Psidium cattleyanum", "Myrtaceae", {"space": 4, "hard": 9}),
    ],
    "tropical_fruit": [
        ("Durián", "Durio zibethinus", "Malvaceae", {"space": 12}),
        ("Salak", "Salacca zalacca", "Arecaceae", {"type": "Árbol", "space": 3}),
        ("Langsat", "Lansium parasiticum", "Meliaceae", {"space": 8}),
        ("Santol", "Sandoricum koetjape", "Meliaceae", {"space": 10}),
        ("Mamoncillo", "Melicoccus bijugatus", "Sapindaceae", {"space": 10, "regions": ["tropical", "mesoamerica"], "origin": "native"}),
        ("Abiú", "Pouteria caimito", "Sapotaceae", {"space": 8, "regions": ["tropical"], "origin": "native"}),
        ("Canistel", "Pouteria campechiana", "Sapotaceae", {"space": 8, "regions": ["tropical", "mesoamerica"], "origin": "native"}),
        ("Anona colorada", "Annona reticulata", "Annonaceae", {"space": 6, "regions": ["tropical", "mesoamerica"], "origin": "native"}),
        ("Bilimbi", "Averrhoa bilimbi", "Oxalidaceae", {"space": 6, "edible": 3}),
        ("Pomarrosa", "Syzygium jambos", "Myrtaceae", {"space": 8}),
        ("Manzana de Malaca", "Syzygium malaccense", "Myrtaceae", {"space": 10}),
        ("Jambolán", "Syzygium cumini", "Myrtaceae", {"space": 10, "med": 3}),
        ("Yambo de agua", "Syzygium aqueum", "Myrtaceae", {"space": 8}),
        ("Caimito morado", "Pouteria caimito", "Sapotaceae", {"space": 8, "edible": 4}),
        ("Guaba peluda", "Inga densiflora", "Fabaceae", {"space": 10, "other": 4, "hab": "Fijador de nitrógeno", "regions": ["tropical", "andes", "mesoamerica"], "origin": "native"}),
        ("Cupuazú", "Theobroma grandiflorum", "Malvaceae", {"space": 6, "sun": SUN_SHADE, "regions": ["tropical"], "origin": "native"}),
        ("Copoazú", "Theobroma bicolor", "Malvaceae", {"space": 8, "regions": ["tropical", "mesoamerica"], "origin": "native"}),
        ("Arazá", "Eugenia stipitata", "Myrtaceae", {"space": 4, "regions": ["tropical", "andes"], "origin": "native"}),
        ("Camu camu", "Myrciaria dubia", "Myrtaceae", {"space": 4, "water": "Alta", "med": 4, "regions": ["tropical"], "origin": "native"}),
        ("Naranjilla / Lulo", "Solanum quitoense", "Solanaceae", {"type": "Arbusto", "space": 2, "hard": 10, "regions": ["andes", "tropical"], "origin": "native"}),
    ],
    "tropical_understory": [
        ("Galangal", "Alpinia galanga", "Zingiberaceae", {"type": "Hierba perenne", "space": 1, "med": 3}),
        ("Cilantro culantro / Sacha culantro", "Eryngium foetidum", "Apiaceae", {"type": "Hierba", "space": 0.3, "regions": ["tropical", "mesoamerica"], "origin": "native"}),
        ("Pimienta de cayena", "Capsicum frutescens", "Solanaceae", {"type": "Arbusto", "space": 0.8, "edible": 5, "regions": ["tropical", "mesoamerica"], "origin": "native"}),
        ("Canela", "Cinnamomum verum", "Lauraceae", {"type": "Árbol", "space": 6, "med": 3}),
        ("Clavo de olor", "Syzygium aromaticum", "Myrtaceae", {"type": "Árbol", "space": 6, "med": 3}),
        ("Nuez moscada", "Myristica fragrans", "Myristicaceae", {"type": "Árbol", "space": 8, "med": 3}),
    ],
    "tropical_staple": [
        ("Mandioca dulce", "Manihot esculenta 'dulce'", "Euphorbiaceae", {"type": "Arbusto", "space": 1.2, "water": "Baja", "regions": ["tropical", "mesoamerica"], "origin": "native"}),
        ("Sagú", "Maranta arundinacea", "Marantaceae", {"type": "Hierba", "space": 0.5}),
        ("Ñampí", "Dioscorea trifida", "Dioscoreaceae", {"type": "Enredadera", "space": 0.5, "regions": ["tropical", "mesoamerica"], "origin": "native"}),
        ("Camote de monte", "Ipomoea aquatica", "Convolvulaceae", {"type": "Hierba", "space": 0.4, "water": "Alta", "hab": "Cerca de agua", "edible": 4}),
        ("Espinaca de Malabar", "Basella alba", "Basellaceae", {"type": "Enredadera", "space": 1, "edible": 4}),
        ("Chaya", "Cnidoscolus aconitifolius", "Euphorbiaceae", {"type": "Arbusto", "space": 2, "edible": 4, "med": 3, "regions": ["mesoamerica", "tropical"], "origin": "native"}),
        ("Plátano macho", "Musa × paradisiaca 'Macho'", "Musaceae", {"type": "Árbol", "space": 3, "water": "Alta"}),
    ],
    "tropical_veg": [
        ("Frijol caupí", "Vigna unguiculata", "Fabaceae", {"type": "Enredadera", "space": 0.3, "other": 4, "hab": "Cultivo fijador"}),
        ("Frijol alado", "Psophocarpus tetragonolobus", "Fabaceae", {"space": 0.4, "other": 4, "hab": "Cultivo fijador"}),
        ("Frijol terciopelo", "Mucuna pruriens", "Fabaceae", {"space": 0.5, "edible": 3, "other": 5, "hab": "Abono verde fijador"}),
        ("Lablab", "Lablab purpureus", "Fabaceae", {"space": 0.4, "other": 4, "hab": "Cultivo fijador"}),
        ("Melón amargo", "Momordica charantia", "Cucurbitaceae", {"space": 1.5, "med": 3}),
        ("Calabaza botella", "Lagenaria siceraria", "Cucurbitaceae", {"type": "Enredadera rastrera", "space": 2, "other": 3}),
        ("Esponja vegetal / Luffa", "Luffa aegyptiaca", "Cucurbitaceae", {"space": 2, "other": 4}),
        ("Quimbombó rojo", "Abelmoschus esculentus 'Red'", "Malvaceae", {"type": "Hierba", "space": 0.5}),
        ("Berenjena tailandesa", "Solanum melongena 'Thai'", "Solanaceae", {"type": "Hierba", "space": 0.6}),
    ],
    "nfixer_tree": [
        ("Sesbania", "Sesbania grandiflora", "Fabaceae", {"edible": 3, "regions": ["tropical", "subtropical"]}),
        ("Calliandra", "Calliandra calothyrsus", "Fabaceae", {"type": "Arbusto", "space": 3, "edible": 1}),
        ("Acacia de Senegal", "Senegalia senegal", "Fabaceae", {"water": "Baja", "other": 4, "regions": ["subtropical"]}),
        ("Faidherbia", "Faidherbia albida", "Fabaceae", {"space": 10, "water": "Baja", "regions": ["subtropical", "tropical"]}),
        ("Flamboyán azul", "Jacaranda mimosifolia", "Bignoniaceae", {"edible": 0, "med": 1, "other": 4, "hab": "Sombra ornamental", "regions": ["subtropical"], "origin": "adapted"}),
        ("Poró / Bucare", "Erythrina poeppigiana", "Fabaceae", {"hab": "Sombra de café / fijador", "regions": ["tropical", "andes", "mesoamerica"], "origin": "native"}),
        ("Carbonero", "Albizia carbonaria", "Fabaceae", {"regions": ["tropical", "mesoamerica"], "origin": "native"}),
    ],
    "nfixer_temp": [
        ("Algarrobo de miel", "Gleditsia triacanthos", "Fabaceae", {"type": "Árbol", "space": 12, "edible": 3, "hard": 4}),
        ("Retama de olor", "Spartium junceum", "Fabaceae", {"type": "Arbusto", "space": 2, "edible": 0, "other": 4, "regions": ["mediterranean"]}),
        ("Codeso", "Laburnum anagyroides", "Fabaceae", {"type": "Árbol", "space": 5, "edible": 0, "other": 3, "hab": "Ornamental fijador"}),
        ("Lupino perenne", "Lupinus polyphyllus", "Fabaceae", {"type": "Hierba perenne", "space": 0.4, "edible": 1, "hab": "Acumulador fijador"}),
        ("Esparceta", "Onobrychis viciifolia", "Fabaceae", {"type": "Hierba", "space": 0.3, "hab": "Forraje fijador", "other": 4}),
        ("Lenteja", "Lens culinaris", "Fabaceae", {"type": "Hierba", "space": 0.2, "edible": 5, "annual": True, "regions": ["mediterranean", "temperate"]}),
        ("Garbanzo", "Cicer arietinum", "Fabaceae", {"type": "Hierba", "space": 0.3, "edible": 5, "annual": True, "regions": ["mediterranean", "subtropical"]}),
        ("Soya", "Glycine max", "Fabaceae", {"type": "Hierba", "space": 0.3, "edible": 5, "annual": True, "regions": ["temperate", "subtropical"]}),
        ("Crotalaria", "Crotalaria juncea", "Fabaceae", {"type": "Arbusto", "space": 1, "edible": 0, "hab": "Abono verde fijador", "regions": ["tropical", "subtropical"]}),
    ],
    "legume_grain": [
        ("Frijol lima", "Phaseolus lunatus", "Fabaceae", {"regions": ["mesoamerica", "andes"], "origin": "native"}),
        ("Frijol escarlata", "Phaseolus coccineus", "Fabaceae", {"type": "Enredadera", "space": 0.3, "regions": ["mesoamerica"], "origin": "native"}),
        ("Frijol tepari", "Phaseolus acutifolius", "Fabaceae", {"water": "Baja", "regions": ["mesoamerica"], "origin": "native"}),
        ("Arveja de campo", "Pisum sativum var. arvense", "Fabaceae", {"hab": "Abono verde fijador"}),
        ("Altramuz azul", "Lupinus angustifolius", "Fabaceae", {"edible": 3}),
    ],
    "veg_annual": [
        ("Puerro", "Allium ampeloprasum var. porrum", "Amaryllidaceae", {"space": 0.2, "hard": 5}),
        ("Chalota", "Allium cepa var. aggregatum", "Amaryllidaceae", {"space": 0.15}),
        ("Apio", "Apium graveolens", "Apiaceae", {"space": 0.3}),
        ("Acelga japonesa / Pak choi", "Brassica rapa subsp. chinensis", "Brassicaceae", {"type": "Hierba", "space": 0.3}),
        ("Colirrábano", "Brassica oleracea var. gongylodes", "Brassicaceae", {"space": 0.3}),
        ("Coles de Bruselas", "Brassica oleracea var. gemmifera", "Brassicaceae", {"space": 0.5, "hard": 5}),
        ("Maíz dulce", "Zea mays var. saccharata", "Poaceae", {"type": "Hierba alta", "space": 0.3, "regions": ["mesoamerica", "temperate"], "origin": "adapted"}),
    ],
    "root_annual": [
        ("Rábano daikon", "Raphanus sativus var. longipinnatus", "Brassicaceae", {"space": 0.2, "other": 3, "hab": "Descompactador"}),
        ("Escorzonera", "Scorzonera hispanica", "Asteraceae", {"space": 0.15, "type": "Raíz"}),
        ("Nabo sueco", "Brassica napobrassica", "Brassicaceae", {"space": 0.3}),
        ("Crosne", "Stachys affinis", "Lamiaceae", {"type": "Raíz", "space": 0.3, "hard": 5}),
    ],
    "leafy": [
        ("Endivia", "Cichorium endivia", "Asteraceae", {"space": 0.3}),
        ("Canónigos", "Valerianella locusta", "Caprifoliaceae", {"space": 0.15}),
        ("Mostaza parda", "Brassica juncea", "Brassicaceae", {"space": 0.3}),
        ("Tatsoi", "Brassica rapa var. rosularis", "Brassicaceae", {"space": 0.25}),
        ("Verdolaga", "Portulaca oleracea", "Portulacaceae", {"type": "Hierba", "space": 0.2, "med": 2, "hab": "Cobertura comestible"}),
        ("Espinaca de Nueva Zelanda", "Tetragonia tetragonioides", "Aizoaceae", {"space": 0.4}),
        ("Col marina", "Crambe maritima", "Brassicaceae", {"type": "Hierba perenne", "space": 0.5, "hard": 5}),
        ("Buen enrique", "Blitum bonus-henricus", "Amaranthaceae", {"type": "Hierba perenne", "space": 0.3, "hard": 4}),
    ],
    "culinary_herb": [
        ("Perifollo", "Anthriscus cerefolium", "Apiaceae", {"annual": True}),
        ("Ajedrea de jardín", "Satureja hortensis", "Lamiaceae", {"annual": True}),
        ("Levístico / Apio de monte", "Levisticum officinale", "Apiaceae", {"type": "Hierba perenne", "space": 0.6, "hard": 4}),
        ("Pimpinela menor", "Sanguisorba minor", "Rosaceae", {"type": "Hierba perenne", "space": 0.3}),
        ("Monarda / Bergamota", "Monarda didyma", "Lamiaceae", {"type": "Hierba perenne", "space": 0.4, "other": 3, "hab": "Polinizador", "hard": 4}),
        ("Hisopo de anís", "Agastache foeniculum", "Lamiaceae", {"type": "Hierba perenne", "space": 0.4, "other": 4, "hab": "Polinizador"}),
        ("Cebolla egipcia", "Allium × proliferum", "Amaryllidaceae", {"type": "Hierba perenne", "space": 0.2, "hard": 4}),
        ("Ajo de oso", "Allium ursinum", "Amaryllidaceae", {"type": "Hierba", "space": 0.2, "sun": SUN_SHADE, "hab": "Sotobosque", "hard": 4}),
    ],
    "medicinal_herb": [
        ("Matricaria", "Tanacetum parthenium", "Asteraceae", {"space": 0.4, "other": 2}),
        ("Artemisa", "Artemisia vulgaris", "Asteraceae", {"space": 0.6, "other": 3}),
        ("Hierba de San Juan", "Hypericum perforatum", "Hypericaceae", {"space": 0.4}),
        ("Malvavisco", "Althaea officinalis", "Malvaceae", {"space": 0.6, "edible": 3}),
        ("Énula", "Inula helenium", "Asteraceae", {"space": 0.7}),
        ("Salvia roja / Danshen", "Salvia miltiorrhiza", "Lamiaceae", {"space": 0.4}),
        ("Gordolobo", "Verbascum thapsus", "Scrophulariaceae", {"space": 0.5, "other": 2}),
        ("Bardana", "Arctium lappa", "Asteraceae", {"type": "Raíz", "space": 0.5, "edible": 4}),
        ("Consuelda menor", "Symphytum tuberosum", "Boraginaceae", {"space": 0.5, "other": 4, "hab": "Acumulador"}),
        ("Hierbabuena de gato / Nébeda", "Nepeta cataria", "Lamiaceae", {"space": 0.4, "other": 3, "hab": "Polinizador"}),
    ],
    "accumulator": [
        ("Achicoria silvestre", "Cichorium intybus 'wild'", "Asteraceae", {"edible": 3, "other": 4, "hab": "Acumulador / descompactador"}),
        ("Acedera común", "Rumex crispus", "Polygonaceae", {"space": 0.4, "other": 4, "hab": "Acumulador"}),
        ("Consuelda enana", "Symphytum grandiflorum", "Boraginaceae", {"space": 0.4, "hab": "Cobertura acumuladora"}),
        ("Cola de caballo", "Equisetum arvense", "Equisetaceae", {"space": 0.3, "edible": 1, "med": 3, "other": 4, "water": "Alta"}),
    ],
    "cover_crop": [
        ("Trébol rojo", "Trifolium pratense", "Fabaceae", {"hab": "Abono verde fijador", "med": 2}),
        ("Trébol subterráneo", "Trifolium subterraneum", "Fabaceae", {"hab": "Cobertura fijadora"}),
        ("Mostaza parda forrajera", "Brassica juncea 'cover'", "Brassicaceae", {"hab": "Biofumigante"}),
        ("Rábano forrajero", "Raphanus sativus var. oleiformis", "Brassicaceae", {"hab": "Descompactador", "other": 4}),
        ("Trébol de Alejandría", "Trifolium alexandrinum", "Fabaceae", {"hab": "Abono verde fijador"}),
    ],
    "grain": [
        ("Espelta", "Triticum spelta", "Poaceae"),
        ("Escanda menor", "Triticum monococcum", "Poaceae"),
        ("Teff", "Eragrostis tef", "Poaceae", {"hard": 9, "regions": ["subtropical", "tropical"]}),
        ("Mijo africano / Eleusine", "Eleusine coracana", "Poaceae", {"hard": 9, "water": "Baja", "regions": ["subtropical", "tropical"]}),
        ("Mijo cola de zorra", "Setaria italica", "Poaceae", {"hard": 8, "water": "Baja"}),
        ("Lágrimas de Job", "Coix lacryma-jobi", "Poaceae", {"hard": 9, "water": "Alta", "regions": ["tropical", "subtropical"]}),
        ("Triticale", "× Triticosecale", "Poaceae"),
    ],
    "andean": [
        ("Arracacha", "Arracacia xanthorrhiza", "Apiaceae", {"type": "Raíz", "space": 0.5, "edible": 5}),
        ("Mauka", "Mirabilis expansa", "Nyctaginaceae", {"type": "Raíz", "space": 0.4}),
        ("Papa amarga", "Solanum juzepczukii", "Solanaceae", {"type": "Raíz", "space": 0.4, "hard": 4}),
        ("Chago / Mauka", "Mirabilis extensa", "Nyctaginaceae", {"type": "Raíz", "space": 0.4}),
        ("Pepino dulce", "Solanum muricatum", "Solanaceae", {"type": "Arbusto", "space": 1, "hard": 9, "edible": 4}),
        ("Capulí", "Prunus serotina subsp. capuli", "Rosaceae", {"type": "Árbol", "space": 8, "hard": 8, "edible": 4}),
    ],
    "vine_fruit": [
        ("Maracuyá morado", "Passiflora edulis f. edulis", "Passifloraceae", {"hard": 9, "hab": "Pérgola", "regions": ["subtropical", "andes"], "origin": "native"}),
        ("Curuba", "Passiflora tarminiana", "Passifloraceae", {"hard": 9, "regions": ["andes"], "origin": "native"}),
        ("Tumbo", "Passiflora mollissima", "Passifloraceae", {"hard": 9, "regions": ["andes"], "origin": "native"}),
        ("Schisandra", "Schisandra chinensis", "Schisandraceae", {"space": 3, "med": 4, "hard": 4}),
        ("Magnolia vid / Akebia trifoliada", "Akebia trifoliata", "Lardizabalaceae", {"space": 3, "hard": 5, "edible": 3}),
        ("Chuchuhuasi", "Maytenus laevis", "Celastraceae", {"type": "Árbol", "space": 6, "edible": 0, "med": 4, "regions": ["tropical", "andes"], "origin": "native"}),
    ],
    "useful_tree": [
        ("Mimbre", "Salix viminalis", "Salicaceae", {"space": 5, "other": 5, "hab": "Cestería / biomasa", "water": "Alta"}),
        ("Aliso andino", "Alnus acuminata", "Betulaceae", {"space": 10, "other": 5, "hab": "Fijador andino", "hard": 8, "regions": ["andes"], "origin": "native"}),
        ("Quillay", "Quillaja saponaria", "Quillajaceae", {"space": 8, "med": 3, "other": 4, "hard": 8, "regions": ["mediterranean", "andes"], "origin": "native"}),
        ("Neem", "Azadirachta indica", "Meliaceae", {"space": 8, "med": 4, "other": 5, "hard": 10, "hab": "Plaguicida natural", "regions": ["tropical", "subtropical"], "origin": "adapted"}),
        ("Eucalipto", "Eucalyptus globulus", "Myrtaceae", {"space": 10, "med": 3, "other": 4, "hard": 8, "regions": ["mediterranean", "subtropical"], "origin": "adapted"}),
        ("Casuarina", "Casuarina equisetifolia", "Casuarinaceae", {"space": 10, "other": 5, "hab": "Cortaviento fijador", "hard": 9, "regions": ["tropical", "subtropical"]}),
        ("Balso / Balsa", "Ochroma pyramidale", "Malvaceae", {"space": 10, "edible": 0, "other": 5, "hab": "Pionera de madera", "hard": 10, "regions": ["tropical", "mesoamerica"], "origin": "native"}),
        ("Cecropia / Guarumo", "Cecropia peltata", "Urticaceae", {"space": 8, "edible": 2, "other": 4, "hab": "Pionera tropical", "hard": 10, "regions": ["tropical", "mesoamerica"], "origin": "native"}),
        ("Sangregado / Drago", "Croton lechleri", "Euphorbiaceae", {"space": 8, "med": 5, "hab": "Medicinal tropical", "hard": 10, "regions": ["tropical", "andes"], "origin": "native"}),
    ],
    "palm": [
        ("Palma jelly / Butiá", "Butia capitata", "Arecaceae", {"space": 5, "hard": 8, "regions": ["subtropical"], "origin": "native"}),
        ("Palmito / Palmera de repollo", "Euterpe edulis", "Arecaceae", {"space": 5, "edible": 4, "regions": ["tropical", "subtropical"], "origin": "native"}),
        ("Corozo / Palma de vino", "Acrocomia aculeata", "Arecaceae", {"space": 8, "regions": ["tropical", "mesoamerica"], "origin": "native"}),
        ("Sagú verdadero", "Metroxylon sagu", "Arecaceae", {"space": 8, "water": "Alta", "edible": 4, "hab": "Humedal tropical"}),
        ("Palma datilera de monte", "Phoenix sylvestris", "Arecaceae", {"space": 8, "water": "Baja", "hard": 9, "regions": ["subtropical", "tropical"]}),
    ],
    "aquatic": [
        ("Loto sagrado", "Nelumbo nucifera", "Nelumbonaceae", {"space": 1.5, "med": 2, "regions": ["subtropical", "tropical"]}),
        ("Espadaña / Totora", "Typha latifolia", "Typhaceae", {"space": 0.6, "edible": 3, "other": 3, "hab": "Fitodepuración"}),
        ("Arroz salvaje", "Zizania aquatica", "Poaceae", {"space": 0.4, "edible": 5, "annual": True}),
        ("Saeta / Wapato", "Sagittaria latifolia", "Alismataceae", {"type": "Raíz", "space": 0.4, "edible": 4}),
        ("Castaña de agua china", "Eleocharis dulcis", "Cyperaceae", {"type": "Raíz", "space": 0.3, "edible": 4, "hard": 9}),
        ("Berro de agua", "Nasturtium microphyllum", "Brassicaceae", {"space": 0.2, "edible": 4}),
        ("Menta acuática", "Mentha aquatica", "Lamiaceae", {"space": 0.4, "edible": 3, "med": 3}),
    ],
    "fiber_dye": [
        ("Lino", "Linum usitatissimum", "Linaceae", {"type": "Hierba", "space": 0.15, "edible": 4, "hard": 5, "hab": "Fibra / semilla", "annual": True}),
        ("Cáñamo", "Cannabis sativa", "Cannabaceae", {"type": "Hierba alta", "space": 0.4, "edible": 3, "annual": True}),
        ("Algodón", "Gossypium hirsutum", "Malvaceae", {"type": "Arbusto", "space": 1, "edible": 1, "hard": 9, "regions": ["subtropical", "tropical"]}),
        ("Agave / Maguey", "Agave americana", "Asparagaceae", {"type": "Arbusto", "space": 2, "water": "Baja", "edible": 3, "soil": "Seco / Drenado", "hard": 8, "regions": ["mesoamerica", "mediterranean"], "origin": "native", "hab": "Fibra / agua-miel"}),
        ("Sisal", "Agave sisalana", "Asparagaceae", {"type": "Arbusto", "space": 2, "water": "Baja", "edible": 0, "hard": 9, "regions": ["subtropical", "tropical"]}),
        ("Achiote tinte", "Bixa orellana 'dye'", "Bixaceae", {"type": "Arbusto", "space": 3, "edible": 2, "hard": 10, "regions": ["tropical", "mesoamerica"], "origin": "native"}),
        ("Índigo", "Indigofera tinctoria", "Fabaceae", {"type": "Arbusto", "space": 1, "edible": 0, "other": 5, "hard": 10, "hab": "Tinte / fijador", "regions": ["tropical", "subtropical"]}),
        ("Rubia", "Rubia tinctorum", "Rubiaceae", {"type": "Hierba perenne", "space": 0.4, "edible": 0, "med": 2, "hab": "Tinte rojo", "regions": ["mediterranean", "temperate"]}),
    ],
}


# ── Third batch: balance regions, cross 500 ──
SPECIES_EXTRA2: dict[str, list] = {
    "andean": [
        ("Quinua roja", "Chenopodium quinoa 'Roja'", "Amaranthaceae", {"type": "Hierba", "space": 0.5}),
        ("Tarwi andino", "Lupinus mutabilis 'andino'", "Fabaceae", {"type": "Hierba", "space": 0.4, "other": 4, "hab": "Fijador de nitrógeno"}),
        ("Maíz morado", "Zea mays 'Morado'", "Poaceae", {"type": "Hierba alta", "space": 0.3, "med": 2}),
        ("Tomate de árbol naranja", "Solanum betaceum 'Naranja'", "Solanaceae", {"type": "Árbol", "space": 3, "hard": 9, "edible": 5}),
        ("Sauco andino", "Sambucus peruviana", "Adoxaceae", {"type": "Árbol", "space": 5, "edible": 3, "med": 4, "hard": 8}),
        ("Molle / Pimiento", "Schinus molle", "Anacardiaceae", {"type": "Árbol", "space": 8, "edible": 2, "med": 3, "other": 3, "hard": 8, "water": "Baja"}),
        ("Aliso de río", "Alnus jorullensis", "Betulaceae", {"type": "Árbol", "space": 10, "edible": 0, "other": 5, "hab": "Fijador andino", "hard": 8}),
        ("Ashpa quinua", "Chenopodium hircinum", "Amaranthaceae", {"type": "Hierba", "space": 0.4, "edible": 3}),
        ("Tauri", "Lupinus tauris", "Fabaceae", {"type": "Hierba", "space": 0.4, "edible": 3, "other": 4, "hab": "Fijador de nitrógeno"}),
        ("Yacón blanco", "Smallanthus sonchifolius 'Blanco'", "Asteraceae", {"type": "Raíz", "space": 0.6, "edible": 4}),
    ],
    "tropical_fruit": [
        ("Zapote negro", "Diospyros nigra", "Ebenaceae", {"space": 10, "regions": ["mesoamerica", "tropical"], "origin": "native"}),
        ("Nance", "Byrsonima crassifolia", "Malpighiaceae", {"space": 6, "regions": ["mesoamerica", "tropical"], "origin": "native"}),
        ("Jocote / Ciruela de monte", "Spondias purpurea", "Anacardiaceae", {"space": 8, "regions": ["mesoamerica", "tropical"], "origin": "native"}),
        ("Mombín amarillo", "Spondias mombin", "Anacardiaceae", {"space": 10, "regions": ["tropical", "mesoamerica"], "origin": "native"}),
        ("Pitanga", "Eugenia uniflora", "Myrtaceae", {"space": 4, "med": 2, "regions": ["tropical", "subtropical"], "origin": "native"}),
        ("Grosella estrella", "Phyllanthus acidus", "Phyllanthaceae", {"space": 6}),
        ("Mamey de Cartagena", "Mammea americana", "Calophyllaceae", {"space": 12, "regions": ["tropical", "mesoamerica"], "origin": "native"}),
        ("Guaba machetona", "Inga spectabilis", "Fabaceae", {"space": 12, "other": 4, "hab": "Fijador de nitrógeno", "regions": ["tropical", "mesoamerica"], "origin": "native"}),
        ("Sapote blanco de monte", "Casimiroa tetrameria", "Rutaceae", {"space": 10, "regions": ["mesoamerica"], "origin": "native"}),
        ("Caña fístula", "Cassia fistula", "Fabaceae", {"space": 8, "edible": 1, "med": 3, "other": 3, "hab": "Ornamental fijador"}),
    ],
    "tropical_staple": [
        ("Yautía / Ocumo", "Xanthosoma sagittifolium", "Araceae", {"type": "Raíz", "space": 0.7, "water": "Alta", "regions": ["tropical", "mesoamerica"], "origin": "native"}),
        ("Mafafa", "Xanthosoma violaceum", "Araceae", {"type": "Raíz", "space": 0.7, "water": "Alta", "regions": ["tropical", "mesoamerica"], "origin": "native"}),
        ("Ñame de agua", "Dioscorea bulbifera", "Dioscoreaceae", {"type": "Enredadera", "space": 0.6}),
        ("Frijol mungo", "Vigna radiata", "Fabaceae", {"type": "Hierba", "space": 0.2, "other": 4, "hab": "Cultivo fijador", "annual": True}),
        ("Frijol negro", "Phaseolus vulgaris 'Negro'", "Fabaceae", {"type": "Enredadera", "space": 0.2, "other": 3, "hab": "Cultivo asociado", "regions": ["mesoamerica", "andes"], "origin": "native", "annual": True}),
    ],
    "temperate_fruit": [
        ("Manzano de sidra", "Malus domestica 'Sidra'", "Rosaceae"),
        ("Peral asiático", "Pyrus pyrifolia", "Rosaceae", {"hard": 5}),
        ("Ciruelo japonés", "Prunus salicina", "Rosaceae", {"hard": 5}),
        ("Cereza de Cornualles", "Cornus mas 'Jolico'", "Cornaceae", {"space": 5, "edible": 4}),
        ("Manzano silvestre japonés", "Malus toringo", "Rosaceae", {"edible": 2, "other": 3, "hab": "Polinizador"}),
        ("Almez americano", "Celtis occidentalis", "Cannabaceae", {"space": 12, "edible": 3, "other": 3}),
        ("Cerezo de pájaro", "Prunus padus", "Rosaceae", {"space": 8, "edible": 2, "med": 2, "hard": 3}),
    ],
    "berry_shrub": [
        ("Frambuesa dorada", "Rubus idaeus 'Aurea'", "Rosaceae", {"space": 1.5}),
        ("Mora himalaya", "Rubus armeniacus", "Rosaceae", {"space": 2, "origin": "invasive"}),
        ("Grosella negra rusa", "Ribes nigrum 'Siberia'", "Grossulariaceae", {"hard": 2}),
        ("Baya de Saskatoon enana", "Amelanchier alnifolia 'Regent'", "Rosaceae", {"type": "Arbusto", "space": 1.5, "edible": 4, "hard": 2}),
        ("Escaramujo de perro", "Rosa canina", "Rosaceae", {"type": "Arbusto", "space": 2, "edible": 3, "med": 3, "hab": "Seto"}),
    ],
    "culinary_herb": [
        ("Cilantro de monte", "Coriandrum sativum 'Confetti'", "Apiaceae", {"annual": True}),
        ("Tomillo limón", "Thymus citriodorus", "Lamiaceae", {"type": "Arbusto", "space": 0.3}),
        ("Orégano griego", "Origanum vulgare subsp. hirtum", "Lamiaceae", {"type": "Hierba perenne", "space": 0.4, "hard": 5}),
        ("Cebolla de invierno", "Allium fistulosum", "Amaryllidaceae", {"type": "Hierba perenne", "space": 0.2, "hard": 4}),
        ("Albahaca sagrada / Tulsi", "Ocimum tenuiflorum", "Lamiaceae", {"type": "Hierba", "space": 0.4, "med": 4, "hard": 10, "regions": ["tropical", "subtropical"], "annual": True}),
    ],
    "medicinal_herb": [
        ("Equinácea pálida", "Echinacea pallida", "Asteraceae", {"space": 0.4, "other": 3}),
        ("Regaliz", "Glycyrrhiza glabra", "Fabaceae", {"type": "Hierba perenne", "space": 0.5, "med": 4, "other": 3, "hab": "Fijador medicinal"}),
        ("Astrágalo", "Astragalus membranaceus", "Fabaceae", {"type": "Hierba perenne", "space": 0.4, "med": 4, "other": 3}),
        ("Salvia de jardín morada", "Salvia officinalis 'Purpurascens'", "Lamiaceae", {"type": "Arbusto", "space": 0.5, "med": 4}),
        ("Ruibarbo", "Rheum rhabarbarum", "Polygonaceae", {"type": "Hierba perenne", "space": 0.8, "edible": 4, "hard": 3, "hab": "Huerto perenne"}),
    ],
    "useful_tree": [
        ("Catalpa", "Catalpa bignonioides", "Bignoniaceae", {"space": 12, "edible": 0, "med": 1, "other": 4, "hab": "Sombra / madera", "hard": 5}),
        ("Acacia de tres espinas inerme", "Gleditsia triacanthos f. inermis", "Fabaceae", {"space": 12, "edible": 3, "other": 4, "hard": 4}),
        ("Mora de papel", "Broussonetia papyrifera", "Moraceae", {"space": 10, "edible": 2, "other": 4, "hab": "Fibra / pionera", "hard": 6}),
        ("Tipa", "Tipuana tipu", "Fabaceae", {"space": 12, "edible": 0, "other": 5, "hab": "Sombra fijadora", "hard": 9, "regions": ["subtropical", "andes"], "origin": "native"}),
        ("Ceibo / Bucaré", "Erythrina crista-galli", "Fabaceae", {"space": 8, "edible": 0, "other": 4, "hab": "Fijador ornamental", "hard": 9, "regions": ["subtropical", "andes"], "origin": "native"}),
    ],
}


# ── Fourth batch: mesoamerica depth, andes, tropical agroforestry, bamboo ──
CATEGORIES.update({
    "mesoamerica_tree": dict(type="Árbol", space=10, sun=SUN_FULL, water="Media", soil="Rico",
        hard=11, edible=2, med=2, other=4, hab="Dosel mesoamericano", regions=["mesoamerica", "tropical"], origin="native"),
    "mesoamerica_herb": dict(type="Hierba perenne", space=0.5, sun=SUN_PART, water="Media", soil="Rico",
        hard=11, edible=3, med=4, other=2, hab="Hierba mesoamericana", regions=["mesoamerica", "tropical"], origin="native"),
    "andes_native": dict(type="Árbol", space=6, sun=SUN_FULL, water="Media", soil="Pobre",
        hard=7, edible=2, med=3, other=3, hab="Nativo andino", regions=["andes"], origin="native"),
    "tropical_agroforestry": dict(type="Árbol", space=6, sun=SUN_SHADE, water="Alta", soil="Rico",
        hard=11, edible=4, med=2, other=3, hab="Agroforestal sombra", regions=["tropical", "mesoamerica"], origin="adapted"),
    "subtropical_medicinal": dict(type="Hierba perenne", space=0.5, sun=SUN_PART, water="Media", soil="Ligero",
        hard=9, edible=2, med=5, other=2, hab="Medicinal subtropical", regions=["subtropical", "tropical", "mesoamerica"], origin="native"),
    "tropical_bamboo": dict(type="Hierba alta", space=5, sun=SUN_FULL, water="Alta", soil="Rico",
        hard=10, edible=2, med=1, other=5, hab="Bambú tropical", regions=["tropical", "mesoamerica"], origin="native"),
    "tropical_pioneer": dict(type="Árbol", space=5, sun=SUN_FULL, water="Baja", soil="Pobre",
        hard=10, edible=1, med=1, other=5, hab="Pionera restauración tropical", regions=["tropical"], origin="native"),
})

SPECIES_EXTRA3: dict[str, list] = {
    # ── Sacred and productive canopy trees of Mesoamerica ──
    "mesoamerica_tree": [
        ("Ceiba / Yaxché", "Ceiba pentandra", "Malvaceae",
            {"space": 20, "edible": 1, "med": 2, "other": 5, "hab": "Árbol sagrado maya / canopeo"}),
        ("Ramón / Ojoche", "Brosimum alicastrum", "Moraceae",
            {"space": 12, "edible": 5, "med": 2, "other": 2, "hab": "Nuez maya alta proteína"}),
        ("Jabín", "Piscidia piscipula", "Fabaceae",
            {"space": 8, "edible": 1, "med": 2, "other": 4, "hab": "Fijador de nitrógeno / miel"}),
        ("Tzalam", "Lysiloma latisiliquum", "Fabaceae",
            {"space": 10, "edible": 0, "other": 5, "hab": "Leguminosa maderera Yucatán"}),
        ("Guapinol / Locust", "Hymenaea courbaril", "Fabaceae",
            {"space": 15, "edible": 3, "med": 3, "other": 4, "hab": "Fijador / resina / vainas"}),
        ("Cedro rojo", "Cedrela odorata", "Meliaceae",
            {"space": 15, "edible": 0, "med": 2, "other": 5, "hab": "Madera preciosa mesoamericana"}),
        ("Palo mulato / Copal colorado", "Bursera simaruba", "Burseraceae",
            {"space": 10, "edible": 0, "med": 3, "other": 4, "hab": "Pionera / corteza medicinal"}),
        ("Guanacastle / Parota", "Enterolobium cyclocarpum", "Fabaceae",
            {"space": 20, "edible": 2, "other": 5, "hab": "Fijador de nitrógeno / forraje"}),
        ("Ilama", "Annona diversifolia", "Annonaceae",
            {"space": 6, "edible": 5, "hab": "Fruta mesoamericana nativa"}),
        ("Pimienta gorda / Allspice", "Pimenta dioica", "Myrtaceae",
            {"space": 6, "edible": 4, "med": 3, "other": 2, "hab": "Especia icónica mesoamericana", "sun": SUN_SHADE}),
        ("Copal blanco", "Bursera copallifera", "Burseraceae",
            {"space": 8, "edible": 0, "med": 3, "other": 4, "hab": "Resina sagrada mesoamericana"}),
        ("Caoba de Honduras", "Swietenia macrophylla", "Meliaceae",
            {"space": 20, "edible": 0, "other": 5, "hab": "Madera preciosa / sombra agroforestal"}),
        ("Chakté kok / Campeche", "Haematoxylum campechianum", "Fabaceae",
            {"space": 8, "edible": 0, "med": 2, "other": 4, "hab": "Tinte / madera dura Yucatán"}),
        ("Chicle / Chico zapote silvestre", "Manilkara chicle", "Sapotaceae",
            {"space": 10, "edible": 3, "other": 3, "hab": "Látex / fruta mesoamerica"}),
        ("Maculís / Palo de rosa", "Tabebuia rosea", "Bignoniaceae",
            {"space": 12, "edible": 0, "med": 2, "other": 4, "hab": "Madera / polinizador"}),
    ],
    # ── Traditional herbs and leaf vegetables of Mesoamerica ──
    "mesoamerica_herb": [
        ("Epazote", "Dysphania ambrosioides", "Amaranthaceae",
            {"space": 0.4, "type": "Hierba", "edible": 4, "med": 3, "hab": "Culinario / medicinal mesoamericano", "annual": True}),
        ("Hoja santa", "Piper auritum", "Piperaceae",
            {"space": 1.5, "type": "Arbusto", "edible": 4, "med": 2, "hab": "Hierba sagrada mesoamericana", "sun": SUN_SHADE}),
        ("Chipilín", "Crotalaria longirostrata", "Fabaceae",
            {"space": 1.0, "type": "Arbusto", "edible": 4, "med": 2, "other": 4, "hab": "Fijador / hoja comestible"}),
        ("Chan / Chía negra", "Hyptis suaveolens", "Lamiaceae",
            {"space": 0.6, "type": "Hierba", "edible": 3, "med": 2, "other": 3, "hab": "Semilla mucilaginosa local", "annual": True}),
        ("Hierba mora", "Solanum nigrescens", "Solanaceae",
            {"space": 0.4, "type": "Hierba", "edible": 3, "med": 2, "hab": "Quelite tradicional tropical"}),
        ("Izote / Palma yuca", "Yucca guatemalensis", "Asparagaceae",
            {"space": 3, "type": "Árbol", "edible": 4, "med": 2, "other": 3, "hab": "Flor comestible / cerca viva"}),
        ("Quelite morado", "Amaranthus hybridus", "Amaranthaceae",
            {"space": 0.4, "type": "Hierba", "edible": 4, "med": 1, "hab": "Quelite comestible", "annual": True}),
        ("Chepiche", "Porophyllum ruderale", "Asteraceae",
            {"space": 0.4, "type": "Hierba", "edible": 3, "med": 2, "hab": "Sustituto del cilantro tropical", "annual": True}),
        ("Loroco", "Fernaldia pandurata", "Apocynaceae",
            {"space": 3, "type": "Enredadera", "edible": 4, "med": 1, "hab": "Flor comestible / pérgola"}),
        ("Orégano mexicano", "Lippia graveolens", "Verbenaceae",
            {"space": 0.8, "type": "Arbusto", "edible": 4, "med": 3, "other": 2, "hab": "Orégano nativo mesoamerica", "hard": 9}),
        ("Chaya de monte", "Cnidoscolus spinosus", "Euphorbiaceae",
            {"space": 2, "type": "Arbusto", "edible": 4, "med": 2, "hab": "Espinaca árbol silvestre"}),
        ("Hierba santa / Momo", "Piper sanctum", "Piperaceae",
            {"space": 1.5, "type": "Arbusto", "edible": 3, "med": 3, "hab": "Condimento mesoamerica", "sun": SUN_SHADE}),
        ("Tomate milpero / Tomatillo real", "Physalis ixocarpa", "Solanaceae",
            {"space": 0.6, "type": "Hierba", "edible": 5, "hab": "Cultivo milpa", "annual": True}),
        ("Chile de agua / Chiltepín", "Capsicum annuum var. glabriusculum", "Solanaceae",
            {"space": 0.8, "type": "Arbusto", "edible": 4, "med": 2, "hab": "Chile nativo mesoamerica", "hard": 10}),
        ("Albahaca mesoamericana", "Ocimum campechianum", "Lamiaceae",
            {"space": 0.4, "type": "Hierba", "edible": 3, "med": 3, "other": 2, "hab": "Albahaca nativa mesoamerica", "annual": True}),
    ],
    # ── Native Andean trees, shrubs, and medicinals ──
    "andes_native": [
        ("Tara", "Caesalpinia spinosa", "Fabaceae",
            {"space": 8, "edible": 1, "med": 3, "other": 5, "hab": "Tanino / fijador / medicina", "water": "Baja"}),
        ("Queñoa", "Polylepis incana", "Rosaceae",
            {"space": 5, "edible": 0, "other": 4, "hab": "Árbol nativo de altura andina", "hard": 6}),
        ("Mutuy", "Cassia tomentosa", "Fabaceae",
            {"space": 3, "type": "Arbusto", "edible": 0, "med": 4, "other": 3, "hab": "Medicinal andino / seto"}),
        ("Matico", "Piper aduncum", "Piperaceae",
            {"space": 3, "type": "Arbusto", "edible": 0, "med": 5, "other": 2, "hab": "Medicinal tropical andino"}),
        ("Muña", "Minthostachys mollis", "Lamiaceae",
            {"space": 0.5, "type": "Arbusto", "edible": 3, "med": 5, "other": 2, "hab": "Menta andina / digestiva"}),
        ("Chachacoma", "Escallonia resinosa", "Escalloniaceae",
            {"space": 4, "type": "Arbusto", "edible": 0, "med": 3, "other": 4, "hab": "Leña andina / medicinal"}),
        ("Quinacho / Quishuar", "Buddleja coriacea", "Scrophulariaceae",
            {"space": 8, "edible": 0, "med": 3, "other": 4, "hab": "Árbol sagrado andino / leña"}),
        ("Cantuta", "Cantua buxifolia", "Polemoniaceae",
            {"space": 2, "type": "Arbusto", "edible": 0, "med": 2, "other": 3, "hab": "Flor sagrada andina"}),
        ("Arrayán andino", "Myrcianthes mato", "Myrtaceae",
            {"space": 4, "edible": 3, "med": 2, "other": 2, "hab": "Fruta andina / miel", "hard": 8}),
        ("Huamanpinta", "Chuquiragua spinosa", "Asteraceae",
            {"space": 0.8, "type": "Arbusto", "edible": 0, "med": 5, "other": 2, "hab": "Flor del montañero andino", "hard": 6}),
        ("Porte / Sauce amargo", "Salix humboldtiana", "Salicaceae",
            {"space": 8, "edible": 0, "med": 3, "other": 4, "hab": "Ribera andina / cestería", "water": "Alta"}),
        ("Lloque", "Kageneckia lanceolata", "Rosaceae",
            {"space": 5, "edible": 0, "other": 4, "hab": "Árbol andino multipropósito"}),
    ],
    # ── Understory crops for tropical agroforestry systems ──
    "tropical_agroforestry": [
        ("Cacao", "Theobroma cacao", "Malvaceae",
            {"space": 4, "edible": 5, "med": 2, "other": 3, "hab": "Cultivo icónico sotobosque tropical", "sun": SUN_SHADE,
             "regions": ["mesoamerica", "tropical"], "origin": "native"}),
        ("Café arábica", "Coffea arabica", "Rubiaceae",
            {"space": 3, "edible": 4, "med": 2, "other": 2, "hab": "Café sotobosque / agroforestal",
             "regions": ["tropical", "subtropical", "andes"], "origin": "adapted"}),
        ("Café robusta", "Coffea canephora", "Rubiaceae",
            {"space": 3, "edible": 4, "other": 2, "hab": "Café de tierras bajas tropicales",
             "regions": ["tropical"], "origin": "adapted"}),
        ("Inga de sombra / Guaba de café", "Inga paterno", "Fabaceae",
            {"space": 8, "edible": 3, "other": 5, "hab": "Sombra del cafetal / fijador",
             "sun": SUN_FULL, "regions": ["mesoamerica", "tropical"], "origin": "native"}),
        ("Macadamia silvestre", "Macadamia tetraphylla", "Proteaceae",
            {"space": 8, "edible": 5, "other": 2, "hab": "Nuez agroforestal subtropical"}),
        ("Guanábana de monte", "Annona glabra", "Annonaceae",
            {"space": 6, "edible": 3, "med": 2, "hab": "Fruta silvestre / portainjertos",
             "regions": ["tropical", "mesoamerica"], "origin": "native"}),
        ("Saman / Árbol de lluvia", "Samanea saman", "Fabaceae",
            {"space": 20, "edible": 2, "other": 5, "hab": "Sombra / fijador / forraje", "sun": SUN_FULL,
             "regions": ["tropical", "mesoamerica"], "origin": "native"}),
        ("Caoba de Las Antillas", "Swietenia mahagoni", "Meliaceae",
            {"space": 15, "edible": 0, "other": 5, "hab": "Madera preciosa / sombra",
             "regions": ["tropical", "mesoamerica"], "origin": "native"}),
    ],
    # ── Medicinal and functional plants of subtropical/tropical regions ──
    "subtropical_medicinal": [
        ("Aloe vera", "Aloe vera", "Asphodelaceae",
            {"space": 0.6, "type": "Arbusto", "edible": 2, "med": 5, "other": 3, "water": "Baja", "soil": "Drenado",
             "regions": ["subtropical", "mediterranean", "tropical"], "origin": "adapted"}),
        ("Yerba mate", "Ilex paraguariensis", "Aquifoliaceae",
            {"space": 4, "type": "Árbol", "edible": 4, "med": 3, "hab": "Estimulante / sotobosque",
             "sun": SUN_SHADE, "regions": ["subtropical", "tropical"], "origin": "native"}),
        ("Uña de gato", "Uncaria guianensis", "Rubiaceae",
            {"space": 3, "type": "Enredadera", "edible": 0, "med": 5, "other": 2, "hab": "Enredadera medicinal",
             "regions": ["tropical"], "origin": "native"}),
        ("Siempreviva / Hoja del aire", "Kalanchoe pinnata", "Crassulaceae",
            {"space": 0.4, "type": "Hierba perenne", "edible": 2, "med": 5, "other": 1, "water": "Baja",
             "regions": ["tropical", "subtropical", "mesoamerica"], "origin": "adapted"}),
        ("Copaíba", "Copaifera langsdorffii", "Fabaceae",
            {"space": 15, "type": "Árbol", "edible": 0, "med": 5, "other": 3, "hab": "Resina antiinflamatoria",
             "regions": ["tropical"], "origin": "native"}),
        ("Guaraná", "Paullinia cupana", "Sapindaceae",
            {"space": 2, "type": "Enredadera", "edible": 3, "med": 4, "hab": "Enredadera estimulante",
             "regions": ["tropical"], "origin": "native"}),
        ("Chuchuhuasi", "Maytenus laevis", "Celastraceae",
            {"space": 8, "type": "Árbol", "edible": 0, "med": 4, "other": 2, "hab": "Tónico / antiinflamatorio",
             "regions": ["tropical", "andes"], "origin": "native"}),
        ("Mastranto", "Hyptis verticillata", "Lamiaceae",
            {"space": 0.6, "type": "Arbusto", "edible": 2, "med": 4, "other": 2, "hab": "Medicinal tropical / repelente",
             "regions": ["mesoamerica", "tropical"], "origin": "native"}),
        ("Ruda criolla", "Ruta chalapensis", "Rutaceae",
            {"space": 0.5, "type": "Arbusto", "edible": 1, "med": 4, "other": 3, "hab": "Medicinal / repelente mesoamerica",
             "regions": ["mesoamerica", "subtropical"], "origin": "native"}),
        ("Verbena medicinal", "Verbena officinalis", "Verbenaceae",
            {"space": 0.4, "type": "Hierba perenne", "edible": 1, "med": 4, "other": 2, "hab": "Medicinal universal"}),
    ],
    # ── Tropical and subtropical bamboo species ──
    "tropical_bamboo": [
        ("Guadua / Bambú gigante americano", "Guadua angustifolia", "Poaceae",
            {"space": 6, "edible": 2, "other": 5, "hab": "Construcción / biomasa / ribera",
             "regions": ["tropical", "andes", "mesoamerica"], "origin": "native", "water": "Alta"}),
        ("Bambú común tropical", "Bambusa vulgaris", "Poaceae",
            {"space": 5, "edible": 2, "other": 4, "hab": "Construcción / biomasa", "regions": ["tropical"]}),
        ("Bambú espinoso / Bambú de la India", "Bambusa bambos", "Poaceae",
            {"space": 6, "edible": 1, "other": 5, "hab": "Cerca viva / cortaviento", "regions": ["tropical"]}),
        ("Bambú gigante asiático", "Dendrocalamus asper", "Poaceae",
            {"space": 8, "edible": 3, "other": 5, "hab": "Brotes comestibles / construcción", "regions": ["tropical"]}),
        ("Bambú de brotes dulces", "Phyllostachys dulcis", "Poaceae",
            {"space": 3, "edible": 4, "other": 3, "hab": "Brotes comestibles", "hard": 7}),
    ],
    # ── Pioneer trees for tropical reforestation ──
    "tropical_pioneer": [
        ("Tithonia / Girasol mexicano", "Tithonia diversifolia", "Asteraceae",
            {"space": 2, "type": "Arbusto", "edible": 0, "med": 1, "other": 5, "hab": "Abono verde / biomasa",
             "regions": ["tropical", "mesoamerica"], "origin": "native"}),
        ("Madre de cacao yucateca", "Gliricidia maculata", "Fabaceae",
            {"space": 5, "edible": 1, "med": 2, "other": 4, "hab": "Fijador / cerca viva endémica Yucatán",
             "regions": ["mesoamerica"], "origin": "native"}),
        ("Helequeme / Poró de cerco", "Erythrina fusca", "Fabaceae",
            {"space": 8, "edible": 0, "other": 4, "hab": "Fijador / sombra / estaca viva",
             "regions": ["tropical", "mesoamerica"], "origin": "native"}),
        ("Yema de huevo / Cradle tree", "Talauma mexicana", "Magnoliaceae",
            {"space": 8, "edible": 0, "med": 2, "other": 3, "hab": "Nativa mesoamerica / sombra",
             "regions": ["mesoamerica"], "origin": "native"}),
        ("Nacascol / Cascalote", "Caesalpinia coriaria", "Fabaceae",
            {"space": 8, "edible": 1, "med": 2, "other": 4, "hab": "Tanino / fijador mesoamerica", "water": "Baja",
             "regions": ["mesoamerica", "subtropical"], "origin": "native"}),
    ],
    # ── Essential tropical fruits missing from previous batches ──
    "tropical_fruit": [
        ("Papaya", "Carica papaya", "Caricaceae",
            {"space": 3, "type": "Árbol", "edible": 5, "med": 3, "hab": "Fruta tropical universal",
             "regions": ["tropical", "mesoamerica", "subtropical"], "origin": "native"}),
        ("Plátano / Banana", "Musa × paradisiaca", "Musaceae",
            {"space": 3, "type": "Árbol", "edible": 5, "med": 1, "other": 2, "water": "Alta",
             "hab": "Fruta tropical universal", "regions": ["tropical", "mesoamerica", "subtropical"]}),
        ("Biribá / Rollinia", "Annona mucosa", "Annonaceae",
            {"space": 6, "edible": 5, "hab": "Fruta tropical brasil-mesoamerica",
             "regions": ["tropical"], "origin": "native"}),
        ("Pitaya andina / Pitahaya amarilla", "Selenicereus megalanthus", "Cactaceae",
            {"space": 2, "type": "Enredadera", "edible": 5, "hab": "Pitahaya amarilla andina",
             "water": "Baja", "regions": ["andes", "tropical"], "origin": "native"}),
        ("Granadilla real / Badea", "Passiflora quadrangularis", "Passifloraceae",
            {"space": 4, "type": "Enredadera", "edible": 5, "med": 2, "hab": "Maracuyá gigante",
             "regions": ["tropical", "andes"], "origin": "native"}),
        ("Icaco / Coco plum", "Chrysobalanus icaco", "Chrysobalanaceae",
            {"space": 3, "type": "Arbusto", "edible": 4, "med": 2, "hab": "Fruta ribera tropical",
             "water": "Alta", "regions": ["tropical", "mesoamerica"], "origin": "native"}),
        ("Anona blanca de monte", "Annona glabra", "Annonaceae",
            {"space": 6, "edible": 3, "med": 2, "hab": "Portainjertos / fruta silvestre",
             "water": "Alta", "regions": ["tropical", "mesoamerica"], "origin": "native"}),
        ("Mamoncillo / Quenepa", "Melicoccus bijugatus", "Sapindaceae",
            {"space": 10, "edible": 4, "hab": "Fruta popular caribe-mesoamerica",
             "regions": ["tropical", "mesoamerica"], "origin": "native"}),
        ("Pepino cohombro", "Solanum muricatum", "Solanaceae",
            {"space": 1, "type": "Arbusto", "edible": 5, "hab": "Pepino andino-subtropical",
             "regions": ["andes", "subtropical"], "origin": "native"}),
    ],
    # ── Mesoamerican and tropical staples ──
    "tropical_staple": [
        ("Yuca / Mandioca", "Manihot esculenta", "Euphorbiaceae",
            {"type": "Arbusto", "space": 1.5, "edible": 5, "med": 1, "other": 2, "water": "Baja",
             "hab": "Raíz andino-tropical básica", "regions": ["tropical", "mesoamerica", "andes"], "origin": "native"}),
        ("Maíz criollo", "Zea mays", "Poaceae",
            {"type": "Hierba alta", "space": 0.4, "edible": 5, "other": 2, "hab": "Milpa / cultivo básico",
             "regions": ["mesoamerica", "andes", "tropical"], "origin": "native", "annual": True}),
        ("Frijol común", "Phaseolus vulgaris", "Fabaceae",
            {"type": "Enredadera", "space": 0.3, "edible": 5, "other": 3, "hab": "Milpa / cultivo fijador",
             "regions": ["mesoamerica", "andes"], "origin": "native", "annual": True}),
        ("Calabaza / Ayote", "Cucurbita moschata", "Cucurbitaceae",
            {"type": "Enredadera rastrera", "space": 2, "edible": 5, "other": 2, "hab": "Milpa / cobertura comestible",
             "regions": ["mesoamerica", "andes", "tropical"], "origin": "native", "annual": True}),
        ("Güicoy / Calabaza pipián", "Cucurbita argyrosperma", "Cucurbitaceae",
            {"type": "Enredadera rastrera", "space": 2, "edible": 5, "other": 2, "hab": "Pepita / milpa mesoamerica",
             "regions": ["mesoamerica"], "origin": "native", "annual": True}),
        ("Chilacayote", "Cucurbita ficifolia", "Cucurbitaceae",
            {"type": "Enredadera rastrera", "space": 2, "edible": 4, "other": 2, "hab": "Calabaza fría mesoamerica",
             "regions": ["mesoamerica", "andes"], "origin": "native", "annual": True}),
    ],
    # ── More andean crops and natives ──
    "andean": [
        ("Quinua blanca", "Chenopodium quinoa 'Blanca'", "Amaranthaceae",
            {"type": "Hierba", "space": 0.5, "edible": 5}),
        ("Maíz chulpi andino", "Zea mays 'Chulpi'", "Poaceae",
            {"type": "Hierba alta", "space": 0.3, "edible": 5, "annual": True}),
        ("Haba andina", "Vicia faba var. andina", "Fabaceae",
            {"type": "Hierba", "space": 0.3, "edible": 5, "other": 3, "hab": "Legumbre / abono verde andino", "annual": True}),
        ("Cebada andina", "Hordeum vulgare var. andinum", "Poaceae",
            {"type": "Hierba", "space": 0.2, "edible": 4, "hab": "Cereal de altura andino", "annual": True}),
        ("Taxo / Curuba de Castilla", "Passiflora tripartita", "Passifloraceae",
            {"type": "Enredadera", "space": 3, "edible": 4, "med": 2, "hab": "Fruta andina / pérgola"}),
        ("Naranjilla de Castilla", "Solanum quitoense var. quitoense", "Solanaceae",
            {"type": "Arbusto", "space": 2, "edible": 4, "hab": "Fruta naranjilla andina", "sun": SUN_SHADE}),
        ("Uvilla andina", "Physalis peruviana var. andina", "Solanaceae",
            {"type": "Hierba perenne", "space": 0.6, "edible": 4, "med": 2}),
        ("Pacay / Guaba andina", "Inga feijoi", "Fabaceae",
            {"space": 8, "edible": 3, "other": 4, "hab": "Fijador de nitrógeno / fruta"}),
    ],
    # ── More nitrogen-fixers for tropical and mesoamerican systems ──
    "nfixer_tree": [
        ("Acacia amarilla / Flamboyán", "Delonix regia", "Fabaceae",
            {"edible": 0, "other": 4, "hab": "Sombra ornamental fijador", "hard": 10,
             "regions": ["tropical", "subtropical"]}),
        ("Acacia mangium", "Acacia mangium", "Fabaceae",
            {"space": 10, "edible": 0, "other": 5, "hab": "Fijador rápido trópico",
             "regions": ["tropical"], "water": "Media"}),
        ("Tephrosia / Indigo silvestre", "Tephrosia candida", "Fabaceae",
            {"type": "Arbusto", "space": 2, "edible": 0, "other": 5, "hab": "Abono verde / fijador tropical",
             "regions": ["tropical", "subtropical"]}),
        ("Mucuna de ábol / Terciopelo arbusto", "Mucuna urens", "Fabaceae",
            {"type": "Enredadera", "space": 3, "edible": 0, "other": 5, "hab": "Fijador trepador tropical",
             "regions": ["tropical", "mesoamerica"], "origin": "native"}),
        ("Flor de palo mesoamerica", "Erythrina berteroana", "Fabaceae",
            {"space": 8, "edible": 2, "other": 4, "hab": "Sombra de café / estaca viva",
             "regions": ["mesoamerica", "tropical"], "origin": "native"}),
    ],
    # ── More temperate and nordic fruits ──
    "temperate_fruit": [
        ("Aronia / Chokeberry negro", "Aronia melanocarpa 'Viking'", "Rosaceae",
            {"type": "Arbusto", "space": 1.5, "med": 4, "hard": 3}),
        ("Morinda blanca", "Morus alba var. multicaulis", "Moraceae",
            {"hard": 5, "edible": 4, "other": 2, "hab": "Morera multiuso"}),
        ("Ciruelo ibérico", "Prunus insititia", "Rosaceae",
            {"space": 4, "hard": 4}),
        ("Tejón / Almez de montaña", "Celtis tournefortii", "Cannabaceae",
            {"space": 8, "edible": 3, "other": 2, "hard": 8}),
    ],
    # ── Additional Mediterranean ──
    "mediterranean": [
        ("Kolatero / Arce de Montpellier", "Acer monspessulanum", "Sapindaceae",
            {"space": 8, "edible": 2, "other": 3, "hab": "Miel / madera"}),
        ("Terebinto", "Pistacia terebinthus", "Anacardiaceae",
            {"type": "Arbusto", "space": 4, "water": "Baja", "edible": 2, "other": 3, "hab": "Trementina / miel"}),
        ("Almendro de montaña", "Prunus webbii", "Rosaceae",
            {"space": 5, "water": "Baja", "edible": 4, "hard": 8}),
    ],
    # ── More medicinal herbs ──
    "medicinal_herb": [
        ("Pasiflora / Flor de la pasión", "Passiflora incarnata", "Passifloraceae",
            {"type": "Enredadera", "space": 3, "edible": 2, "med": 5, "hab": "Sedante / pérgola"}),
        ("Lemon balm silvestre", "Melissa officinalis 'wild'", "Lamiaceae",
            {"space": 0.4, "edible": 3, "med": 4, "hab": "Polinizador / calmante"}),
        ("Angélica", "Angelica archangelica", "Apiaceae",
            {"space": 0.6, "edible": 3, "med": 4, "other": 2, "hab": "Medicinal / polinizador", "water": "Alta"}),
        ("Caléndula de campo salvaje", "Tagetes minuta", "Asteraceae",
            {"space": 0.4, "type": "Hierba", "edible": 1, "med": 3, "other": 4, "hab": "Repelente nematodos",
             "regions": ["andes", "subtropical"], "origin": "native", "annual": True}),
        ("Árnica de campo", "Arnica montana", "Asteraceae",
            {"space": 0.3, "edible": 0, "med": 5, "hab": "Antiinflamatorio externo", "soil": "Ácido", "hard": 3}),
    ],
    # ── Useful trees and multipurpose ──
    "useful_tree": [
        ("Palo de jabón andino", "Quillaja brasiliensis", "Quillajaceae",
            {"space": 8, "edible": 0, "med": 3, "other": 4, "hard": 8, "regions": ["subtropical", "andes"]}),
        ("Jacaranda azul", "Jacaranda mimosifolia", "Bignoniaceae",
            {"space": 10, "edible": 0, "med": 1, "other": 4, "hab": "Sombra ornamental / pionera",
             "hard": 9, "regions": ["subtropical", "andes"], "origin": "adapted"}),
        ("Higuerilla", "Ricinus communis", "Euphorbiaceae",
            {"space": 3, "type": "Arbusto", "edible": 0, "other": 5, "hab": "Aceite / biomasa / repelente",
             "hard": 9, "regions": ["subtropical", "tropical"], "origin": "adapted"}),
        ("Jatrofa / Piñón blanco", "Jatropha curcas", "Euphorbiaceae",
            {"space": 3, "type": "Arbusto", "edible": 0, "other": 5, "hab": "Biocombustible / cerca viva",
             "hard": 10, "water": "Baja", "regions": ["tropical", "mesoamerica"], "origin": "native"}),
        ("Nim / Neem mesoamerica", "Azadirachta indica 'tropical'", "Meliaceae",
            {"space": 8, "med": 4, "other": 5, "hab": "Plaguicida / sombra",
             "hard": 11, "regions": ["mesoamerica", "tropical"]}),
    ],
}


def slugify(sci: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", sci.lower()).strip("-")


def build():
    here = os.path.dirname(__file__)
    db_path = os.path.join(here, "..", "src", "lib", "pfaf", "pfafDb.json")
    with open(db_path, encoding="utf-8") as f:
        existing = json.load(f)

    for batch in (SPECIES_EXTRA, SPECIES_EXTRA2, SPECIES_EXTRA3):
        for cat, items in batch.items():
            SPECIES.setdefault(cat, []).extend(items)

    by_sci = {e["sci"].lower(): e for e in existing}
    out = list(existing)
    next_id = max((int(e["id"].split("-")[1]) for e in existing if e["id"].startswith("pfaf-")), default=0) + 1
    added = 0

    for cat, items in SPECIES.items():
        base = CATEGORIES[cat]
        for item in items:
            n, sci, fam = item[0], item[1], item[2]
            overrides = item[3] if len(item) > 3 else {}
            if sci.lower() in by_sci:
                continue
            entry = {
                "id": f"pfaf-{next_id}",
                "n": n, "sci": sci, "f": fam,
                "type": base["type"], "space": base["space"], "sun": base["sun"],
                "water": base["water"], "soil": base["soil"], "hard": base["hard"],
                "edible": base["edible"], "med": base["med"], "other": base["other"],
                "hab": base["hab"], "regions": list(base["regions"]), "origin": base["origin"],
            }
            if base.get("annual"):
                entry["annual"] = True
            entry.update(overrides)
            if "regions" in overrides:
                entry["regions"] = list(overrides["regions"])
            out.append(entry)
            by_sci[sci.lower()] = entry
            next_id += 1
            added += 1

    # One compact object per line, matching the existing file style.
    lines = ["["]
    for i, e in enumerate(out):
        comma = "," if i < len(out) - 1 else ""
        lines.append("  " + json.dumps(e, ensure_ascii=False) + comma)
    lines.append("]")
    with open(db_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"added {added} species; total {len(out)}")


if __name__ == "__main__":
    build()
