import type { GlyphName } from './glyph-data';

export const PLANT_GLYPH: Record<string, GlyphName> = {
  aguacate: 'Aguacate',
  mango: 'Mango',
  chachafruto: 'Chachafruto',
  guanabana: 'Guanabana',
  platano: 'Platano',
  cafe: 'Cafe',
  yuca: 'Yuca',
  aji: 'Aji',
  frijol: 'Frijol',
  cilantro: 'Cilantro',
  maiz: 'Maiz',
  girasol: 'Girasol',
  cacao: 'Cacao',
  papaya: 'Papaya',
  chile: 'Chile',
  calabaza: 'Calabaza',
  // New PFAF entries → reuse the closest hand-drawn glyph
  guamo: 'Chachafruto',
  papa: 'Yuca',
  quinua: 'Maiz',
  amaranto: 'Maiz',
  tomate: 'Aji',
  cebolla: 'Seed',
  ajo: 'Seed',
  zanahoria: 'Yuca',
  lechuga: 'Cilantro',
  acelga: 'Cilantro',
  espinaca: 'Cilantro',
  rabano: 'Cilantro',
  remolacha: 'Yuca',
  mora: 'Cafe',
  fresa: 'Cilantro',
  ruda: 'Cilantro',
  manzanilla: 'Cilantro',
  hierbabuena: 'Cilantro',
  romero: 'Cafe',
  caña: 'Maiz',
  pina: 'Calabaza',
  pasiflora: 'Frijol',
  lulo: 'Cafe',
  ortiga: 'Cilantro',
  citrico: 'Mango',
  limon: 'Mango',
  guayabo: 'Cafe',
  granadilla: 'Frijol',
  tomate_arbol: 'Aji',
  uchuva: 'Aji',
  curuba: 'Frijol',
  pitaya: 'Calabaza',
  cocotero: 'Platano',
  arazá: 'Cafe',
  copoazu: 'Cacao',
  borojo: 'Cacao',
  acai: 'Platano',
  arracacha: 'Yuca',
  achira: 'Cilantro',
  oca: 'Yuca',
  ulluco: 'Yuca',
  batata: 'Yuca',
  toronjil: 'Cilantro',
  hinojo: 'Cilantro',
  oregano: 'Cilantro',
  albahaca: 'Cilantro',
  tomillo: 'Cilantro',
  lavanda: 'Cilantro',
  citronela: 'Cilantro',
  yerba_mate: 'Cafe',
  guandul: 'Frijol',
  leucaena: 'Chachafruto',
  matarraton: 'Chachafruto',
  habas: 'Frijol',
  alfalfa: 'Cilantro',
  tagetes: 'Girasol',
  arroz: 'Maiz',
  sorgo: 'Maiz'
};

export const ANIMAL_GLYPH: Record<string, GlyphName> = {
  abeja: 'Abeja',
  abejaNativa: 'Abeja',
  mariposa: 'Mariposa',
  lombriz: 'Lombriz',
  hormiga: 'Hormiga',
  arriera: 'Hormiga',
  pajaro: 'Pajaro',
  colibri: 'Pajaro',
  lagartija: 'Lagartija',
  rana: 'Rana',
  topo: 'Topo',
  iguana: 'Iguana',
  cienpies: 'Lombriz',
  milpies: 'Lombriz',
  arana: 'Sparkle',
  mariquita: 'Sparkle',
  aveAvispa: 'Abeja',
  caracol: 'Sparkle',
  babosa: 'Sparkle',
  pulgon: 'Sparkle',
  mosquito: 'Sparkle',
  gallina: 'Pajaro',
  pato: 'Pajaro',
  cerdo: 'Sparkle',
  cabra: 'Sparkle',
  oveja: 'Sparkle',
  serpiente: 'Sparkle',
  roedor: 'Topo',
  murcielago: 'Pajaro',
  lechuza: 'Pajaro',
  gavilan: 'Pajaro',
  tucan: 'Pajaro',
  capibara: 'Topo',
  zorro: 'Sparkle',
  comadreja: 'Topo',
  colmena: 'Abeja',
  avispa_hada: 'Abeja',
  sapito: 'Rana',
  chinche_dep: 'Sparkle'
};

export const PLANT_TONE: Record<string, string> = {
  aguacate: 'var(--jade-deep)',
  mango: 'var(--ocre)',
  chachafruto: 'var(--jade)',
  guanabana: 'var(--jade)',
  platano: 'var(--maiz)',
  cafe: 'var(--ocre-deep)',
  yuca: 'var(--ocre)',
  aji: 'var(--cinabrio)',
  frijol: 'var(--jade-deep)',
  cilantro: 'var(--jade)',
  maiz: 'var(--maiz)',
  girasol: 'var(--maiz)',
  cacao: 'var(--ocre-deep)',
  papaya: 'var(--maiz)',
  chile: 'var(--cinabrio)',
  calabaza: 'var(--ocre)',
  guamo: 'var(--jade)',
  papa: 'var(--ocre-deep)',
  quinua: 'var(--maiz)',
  amaranto: 'var(--cinabrio)',
  tomate: 'var(--cinabrio)',
  cebolla: 'var(--ocre)',
  ajo: 'var(--ocre)',
  zanahoria: 'var(--ocre)',
  lechuga: 'var(--jade)',
  acelga: 'var(--jade)',
  espinaca: 'var(--jade-deep)',
  rabano: 'var(--cinabrio)',
  remolacha: 'var(--cinabrio)',
  mora: 'var(--cinabrio)',
  fresa: 'var(--cinabrio)',
  ruda: 'var(--jade-deep)',
  manzanilla: 'var(--maiz)',
  hierbabuena: 'var(--jade)',
  romero: 'var(--jade-deep)',
  caña: 'var(--maiz)',
  pina: 'var(--maiz)',
  pasiflora: 'var(--cinabrio)',
  lulo: 'var(--maiz)',
  ortiga: 'var(--jade)',
  citrico: 'var(--maiz)',
  limon: 'var(--maiz)',
  guayabo: 'var(--jade)',
  granadilla: 'var(--maiz)',
  tomate_arbol: 'var(--cinabrio)',
  uchuva: 'var(--maiz)',
  curuba: 'var(--jade)',
  pitaya: 'var(--cinabrio)',
  cocotero: 'var(--ocre)',
  arazá: 'var(--maiz)',
  copoazu: 'var(--ocre-deep)',
  borojo: 'var(--ocre-deep)',
  acai: 'var(--cinabrio)',
  arracacha: 'var(--ocre)',
  achira: 'var(--cinabrio)',
  oca: 'var(--ocre)',
  ulluco: 'var(--cinabrio)',
  batata: 'var(--ocre)',
  toronjil: 'var(--jade)',
  hinojo: 'var(--jade)',
  oregano: 'var(--jade-deep)',
  albahaca: 'var(--jade)',
  tomillo: 'var(--jade-deep)',
  lavanda: 'var(--cinabrio)',
  citronela: 'var(--jade)',
  yerba_mate: 'var(--jade-deep)',
  guandul: 'var(--ocre)',
  leucaena: 'var(--jade)',
  matarraton: 'var(--jade)',
  habas: 'var(--jade-deep)',
  alfalfa: 'var(--jade)',
  tagetes: 'var(--maiz)',
  arroz: 'var(--maiz)',
  sorgo: 'var(--maiz)'
};

export function plantGlyph(speciesId: string): GlyphName {
  return PLANT_GLYPH[speciesId] ?? 'Seed';
}

export function animalGlyph(speciesId: string): GlyphName {
  return ANIMAL_GLYPH[speciesId] ?? 'Sparkle';
}

export function plantTone(speciesId: string): string {
  return PLANT_TONE[speciesId] ?? 'var(--ocre)';
}
